---
title: "ACS"
author: "Chris Soria"
date: "2025-03-22"
output: html_document
---

```{r}
library(tidycensus)
```

```{r}
download.file("https://www2.census.gov/programs-surveys/acs/data/pums/2010/3-Year/csv_pus.zip", 
              "acs_3yr_pums.zip")
unzip("acs_3yr_pums.zip")
```


```{r}
ca_acs_data <- get_pums(
  variables = c("NATIVITY", "POBP", "SCHL"),
  state = "CA",
  year = 2010,
  survey = "acs3",
  recode = FALSE
)

ny_acs_data <- get_pums(
  variables = c("SCHL"),
  state = "NY",
  year = 2012,
  survey = "acs5",
  recode = FALSE
)
table(ny_acs_data$SCHL)
```

```{r}
ny_edu <- get_decennial(
  geography = "state",
  variables = c(
    total = "P015001",
    bachelors = "P015022",      # Bachelor's degree (25+ years)
    graduate = "P015023"        # Graduate/professional degree (25+ years)
  ),
  year = 2010,
  sumfile = "sf1"
)

# Results
ny_edu
```


```{r}
library(tidycensus)

# Set your Census API key (if not already set)
census_api_key("7c7cbdb248c76d63e420e726e423f745dc49eb5d")

# Download the data
acs_data <- get_pums(
  variables = c("NATIVITY", "POBP", "SCHL"),
  state = "all",
  year = 2010,
  survey = "acs5",
  recode = TRUE
)

# View the first few rows of the data
head(acs_data)

```

