---
title: "regressions"
author: "Chris Soria"
date: "2025-01-08"
output: html_document
---

```{r}
library(emmeans)
library(tidyverse)
library(broom)
library(cowplot)
library(writexl)
library(scales)
```

```{r}
target_dir <- normalizePath("/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables")
current_dir <- normalizePath(getwd())

if (current_dir == target_dir) {
  out_dir <- file.path("/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/")
  data_dir <- file.path("/Users/chrissoria/Documents/Research/us_international_ses/data/")
  plot_dir <- file.path("/Users/chrissoria/Documents/Research/us_international_ses/plots/")

} else {
  out_dir <- file.path("C:/Users/Ty/Desktop/ses_international/tables/r_tables//")
  data_dir <- file.path("C:/Users/Ty/Desktop/ses_international/data//")
  plot_dir <- file.path("C:/Users/Ty/Desktop/ses_international/plots//")

}

print(getwd())
```
## migrant regressions
```{r}
dvs <- c("married_cohab", "primary_or_above", "secondary_or_above", "is_naturalized_citizen", "english_speaker", "lives_alone")

ivs <- c("age_at_immigration_under15", "age_at_immigration_25to49", "age_at_immigration_50plus", "yrimm_before1965", "yrimm_1965to1980", "yrimm_1980to1999", "yrimm_2000plus", "female", "country_string", "country_string")

us_df_2010_filtered <- us_df_2010 %>% 
   filter(country_string %in% c("mexico", "puerto rico", "dominican republic", "cuba")) %>% 
   mutate(country_string = fct_relevel(country_string, "mexico"))

results_list <- list()

# running the models
for (dv in dvs) {
  formula <- as.formula(paste(dv, "~", paste(ivs, collapse = " + ")))

  print(formula)

  model <- lm(formula, data = us_df_2010_filtered, 
               weights = perwt)

  results_list[[dv]] <- model
}

summaries <- map(results_list, summary)

for (reason in names(summaries)) {
  cat("\n\n", "Summary for", reason, ":\n")
  print(summaries[[reason]])
}

excel_data <- list()

# Loop through each model in results_list
for (reason in names(results_list)) {
  if (!is.null(results_list[[reason]])) {
    model_summary <- tidy(results_list[[reason]])
    
    excel_data[[reason]] <- model_summary
  } else {
    cat("\n\n", "No valid model for", reason, "\n")
  }
}

if (length(excel_data) > 0) {
  write_xlsx(excel_data, path = paste0(out_dir, "../regressions/within_US_model_summaries.xlsx"))
} else {
  cat("No valid data to write to Excel.\n")
}
```
## overall DV emmeans
```{r}
emm_results <- map(results_list, ~ emmeans(.x, specs = "country_string"))

# Convert to tidy data frames with CIs
emm_tables <- map(emm_results, ~ summary(.x, infer = TRUE) %>% 
                  as.data.frame() %>%
                  select(country_string, emmean, SE, lower.CL, upper.CL))

for (dv in dvs) {
  p <- ggplot(emm_tables[[dv]], 
              aes(x = reorder(country_string, emmean), 
                  y = emmean)) +
    geom_col(fill = "#1f78b4", width = 0.7) +
    geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),
                  width = 0.2, color = "black") +
    # Add percentage labels above bars
    geom_text(
      aes(label = percent(emmean, accuracy = 1)),
      vjust = -1.5, 
      color = "black",
      size = 3.5,
      fontface = "bold"
    ) +
    # Convert y-axis to percentage format
    scale_y_continuous(
      labels = percent_format(accuracy = 1),
      expand = expansion(mult = c(0, 0.1))
    ) +
    ylim(0,1) +
    labs(
      title = element_blank(),
      x = element_blank(),
      y = "Estimated Percent"
    ) +
    theme_cowplot() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.text.y = element_blank())
  
  print(p)
  
  ggsave(
    filename = file.path("/Users/chrissoria/Documents/Research/us_international_ses/plots", 
                        paste0(dv, "_emm_plot.png")),
    plot = p,
    device = "png",
    width = 8,
    height = 6,
    dpi = 300
  )
}
```


# migrant-specific regressions
```{r}
dvs <- c("married_cohab", "age_at_immigration_under15", "age_at_immigration_15to49", "age_at_immigration_50plus", "secondary_or_above", "less_than_primary_completed", "primary_completed", "secondary_completed", "university_completed", "yrimm_before1965", "yrimm_1965to1980", "yrimm_1980to1999", "yrimm_2000plus", "is_naturalized_citizen", "female", "english_speaker")

ivs <- c("country_string", "age_70to79", "age_80to89")

us_df_2020_filtered <- us_df_2020 %>% 
   filter(country_string %in% c("mexico", "puerto rico", "dominican republic", "cuba")) %>% 
   mutate(country_string = fct_relevel(country_string, "mexico"))

results_list <- list()

# running the models
for (dv in dvs) {
  formula <- as.formula(paste(dv, "~", paste(ivs, collapse = " + ")))

  print(formula)

  model <- glm(formula, data = us_df_2020_filtered, 
               family = binomial(),
               weights = perwt)

  results_list[[dv]] <- model
}

summaries <- map(results_list, summary)

for (reason in names(summaries)) {
  cat("\n\n", "Summary for", reason, ":\n")
  print(summaries[[reason]])
}

excel_data <- list()

# Loop through each model in results_list
for (reason in names(results_list)) {
  if (!is.null(results_list[[reason]])) {
    model_summary <- tidy(results_list[[reason]])
    
    excel_data[[reason]] <- model_summary
  } else {
    cat("\n\n", "No valid model for", reason, "\n")
  }
}

if (length(excel_data) > 0) {
  write_xlsx(excel_data, path = paste0(out_dir, "../regressions/within_US_model_summaries.xlsx"))
} else {
  cat("No valid data to write to Excel.\n")
}
```
## age at migration correlated with education?
```{r}
run_education_model <- function(data, dv, country) {
  model <- data %>%
    filter(country_string == country) %>%
    glm(as.formula(paste(dv, "~ age + as.factor(female) + race_string + as.factor(english_speaker) + married_cohab + year_of_immig_groups_string + age_at_immig_groups_string")), 
        data = ., 
        family = binomial(),
        weights = perwt)
  
  return(model)
}

primary_completed_model_me <- run_education_model(us_df_2020, "primary_or_above", "mexico")
primary_completed_model_cu <- run_education_model(us_df_2020, "primary_or_above", "cuba")
primary_completed_model_pr <- run_education_model(us_df_2020, "primary_or_above", "puerto rico")
primary_completed_model_dr <- run_education_model(us_df_2020, "primary_or_above", "dominican republic")

summary(primary_completed_model_me)

get_emmeans_summary <- function(model, specs = "age_at_immig_groups_string", age = 65, female = 1, english_speaker = 1, race_string = "white hispanic", year_of_immig_groups_string = "1980 - 1999") {
  emm <- emmeans(model, 
                 specs = specs,
                 at = list(age = age, female = female, english_speaker = english_speaker, race_string = race_string, year_of_immig_groups_string = year_of_immig_groups_string),
                 type = "response")
  
  emm_summary <- transform(summary(emm))
  
  return(emm_summary)
}

emm_primary_completed_model_me <- get_emmeans_summary(primary_completed_model_me) %>% 
  mutate(country = "mexico")
emm_primary_completed_model_cu <- get_emmeans_summary(primary_completed_model_cu) %>% 
  mutate(country = "cuba")
emm_primary_completed_model_pr <- get_emmeans_summary(primary_completed_model_pr) %>% 
  mutate(country = "puerto rico")
emm_primary_completed_model_dr <- get_emmeans_summary(primary_completed_model_dr) %>% 
  mutate(country = "dominican republic")

all_emms_full_controls <- rbind(emm_primary_completed_model_me, emm_primary_completed_model_cu, emm_primary_completed_model_pr, emm_primary_completed_model_dr)

print(all_emms_full_controls)

ggplot(all_emms_full_controls, aes(x = age_at_immig_groups_string, y = prob, color = country, group = country)) +
  geom_point(position = position_dodge(width = 0.2)) +
  geom_line(position = position_dodge(width = 0.2)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1, position = position_dodge(width = 0.2)) +
  labs(x = "Age at Immigration", y = "Probability of Primary Education or Above", 
       title = "Probability of Primary Education or Above by Age at Immigration and Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_brewer(palette = "Set1")

ggsave(paste0(plot_dir, "predicted_primary_education_by_immigration_age_and_country.png"), width = 12, height = 8)
```
## age at migration correlated with citizenship?
```{r}
primary_completed_model_me <- run_education_model(us_df_2020, "is_naturalized_citizen", "mexico")
primary_completed_model_cu <- run_education_model(us_df_2020, "is_naturalized_citizen", "cuba")
primary_completed_model_dr <- run_education_model(us_df_2020, "is_naturalized_citizen", "dominican republic")

summary(primary_completed_model_me)

get_emmeans_summary <- function(model, specs = "age_at_immig_groups_string", age = 65, female = 1, english_speaker = 1, race_string = "white hispanic", year_of_immig_groups_string = "1980 - 1999") {
  emm <- emmeans(model, 
                 specs = specs,
                 at = list(age = age, female = female, english_speaker = english_speaker, race_string = race_string, year_of_immig_groups_string = year_of_immig_groups_string),
                 type = "response")
  
  emm_summary <- transform(summary(emm))
  
  return(emm_summary)
}

emm_primary_completed_model_me <- get_emmeans_summary(primary_completed_model_me) %>% 
  mutate(country = "mexico")
emm_primary_completed_model_cu <- get_emmeans_summary(primary_completed_model_cu) %>% 
  mutate(country = "cuba")
emm_primary_completed_model_dr <- get_emmeans_summary(primary_completed_model_dr) %>% 
  mutate(country = "dominican republic")

all_emms_full_controls <- rbind(emm_primary_completed_model_me, emm_primary_completed_model_cu, emm_primary_completed_model_dr)

print(all_emms_full_controls)

ggplot(all_emms_full_controls, aes(x = age_at_immig_groups_string, y = prob, color = country, group = country)) +
  geom_point(position = position_dodge(width = 0.2)) +
  geom_line(position = position_dodge(width = 0.2)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1, position = position_dodge(width = 0.2)) +
  labs(x = "Age at Immigration", y = "Probability", 
       title = "Probability of Naturalized Citizen by Age at Immigration and Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_brewer(palette = "Set1")

ggsave(paste0(plot_dir, "predicted_citizen_by_immigration_age_and_country.png"), width = 12, height = 8)
```
## age at migration correlated with english speaking?
```{r}
run_education_model <- function(data, dv, country) {
  model <- data %>%
    filter(country_string == country) %>%
    glm(as.formula(paste(dv, "~ age + as.factor(female) + race_string + as.factor(is_naturalized_citizen) + married_cohab + year_of_immig_groups_string + age_at_immig_groups_string" + "country_string")), 
        data = ., 
        family = binomial(),
        weights = perwt)
  
  return(model)
}

primary_completed_model_me <- run_education_model(us_df_2020, "english_speaker", "mexico")
primary_completed_model_cu <- run_education_model(us_df_2020, "english_speaker", "cuba")
primary_completed_model_dr <- run_education_model(us_df_2020, "english_speaker", "dominican republic")

run_education_model <- function(data, dv, country) {
  model <- data %>%
    filter(country_string == country) %>%
    glm(as.formula(paste(dv, "~ age + as.factor(female) + race_string + married_cohab + year_of_immig_groups_string + age_at_immig_groups_string")), 
        data = ., 
        family = binomial(),
        weights = perwt)
  
  return(model)
}

primary_completed_model_pr <- run_education_model(us_df_2020, "english_speaker", "puerto rico")

summary(primary_completed_model_me)

get_emmeans_summary <- function(model, specs = "age_at_immig_groups_string", age = 65, female = 1, race_string = "white hispanic", year_of_immig_groups_string = "1980 - 1999") {
  emm <- emmeans(model, 
                 specs = specs,
                 at = list(age = age, female = female, race_string = race_string, year_of_immig_groups_string = year_of_immig_groups_string),
                 type = "response")
  
  emm_summary <- transform(summary(emm))
  
  return(emm_summary)
}

emm_primary_completed_model_me <- get_emmeans_summary(primary_completed_model_me) %>% 
  mutate(country = "mexico")
emm_primary_completed_model_cu <- get_emmeans_summary(primary_completed_model_cu) %>% 
  mutate(country = "cuba")
emm_primary_completed_model_pr <- get_emmeans_summary(primary_completed_model_pr) %>% 
  mutate(country = "puerto rico")
emm_primary_completed_model_dr <- get_emmeans_summary(primary_completed_model_dr) %>% 
  mutate(country = "dominican republic")

all_emms_full_controls <- rbind(emm_primary_completed_model_me, emm_primary_completed_model_cu, emm_primary_completed_model_pr, emm_primary_completed_model_dr)

print(all_emms_full_controls)

ggplot(all_emms_full_controls, aes(x = age_at_immig_groups_string, y = prob, color = country, group = country)) +
  geom_point(position = position_dodge(width = 0.2)) +
  geom_line(position = position_dodge(width = 0.2)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1, position = position_dodge(width = 0.2)) +
  labs(x = "Age at Immigration", y = "Probability", 
       title = "Probability of Speaking English by Age at Immigration and Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_brewer(palette = "Set1")

ggsave(paste0(plot_dir, "predicted_english_speaking_by_immigration_age_and_country.png"), width = 12, height = 8)
```

