---
title: "tables"
author: "Chris Soria"
date: "2024-09-28"
output: html_document
---

```{r}
library(haven)
library(tidyverse)
library(xtable)
library(kableExtra)
library(readxl)
library(officer)
library(broom)
library(writexl)
library(scales)
library(readr)
```

```{r}
target_dir <- normalizePath("/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables")
current_dir <- normalizePath(getwd())

if (current_dir == target_dir) {
  out_dir <- file.path("/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/")
  data_dir <- file.path("/Users/chrissoria/Documents/Research/us_international_ses/data/")
  plot_dir <- file.path("/Users/chrissoria/Documents/Research/us_international_ses//plots/")

} else {
  out_dir <- file.path("C:/Users/Ty/Desktop/ses_international/tables/r_tables//")
  data_dir <- file.path("C:/Users/Ty/Desktop/ses_international/data//")
  plot_dir <- file.path("C:/Users/Ty/Desktop/ses_international/plots//")

}

print(getwd())
```
## reading in data
```{r}
# US
us_df_2010 <- read_dta(paste0(data_dir, "US_2010_v100.dta"))
us_df_2020 <- read_dta(paste0(data_dir, "US_2020_v100.dta"))

#international censuses
in_df <- read_dta(paste0(data_dir,"CuDrMePrUs_10_12.dta"))

in_df <- in_df %>%
  mutate(country_year = as_factor(country_year))

# background data
gdp <- read_excel(paste0(data_dir, "gdp_per_capita.xlsx"))

countries_of_interest <- c(
  "Puerto Rico",
  "Canada",
  "Mexico",
  "Belize",
  "Costa Rica",
  "El Salvador",
  "Guatemala",
  "Honduras",
  "Nicaragua",
  "Panama",
  "Cuba",
  "Dominican Republic",
  "Haiti",
  "Jamaica",
  "Dominica",
  "Trinidad and Tobago",
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Guyana",
  "Paraguay",
  "Peru",
  "Uruguay",
  "Venezuela",
  "Bolivia (Plurinational State of)",
  "Venezuela (Bolivarian Republic of)"
)

gdp <- gdp %>%
  filter(...1 %in% countries_of_interest) %>% 
  mutate(`2023` = if_else(...1 == "Cuba", "7449.68", `2023`)) %>% #cuba gdp per capita is 2022
  rename(gdp = `2023`,
         country = ...1)

#life expectancy at 60  
# dominica not in the dataset
e60 <- read_csv(paste0(data_dir, "e60.csv")) %>%
  filter(Location %in% countries_of_interest,
         Dim1 == "Both sexes") %>% 
  filter(Period == 2019) %>% 
  filter(Indicator == "Life expectancy at age 60 (years)") %>%
  select(Dim1, Value, Location) %>%
  separate(Value, into = c("e60", "CI_lower", "CI_upper"), 
           sep = " \\[|\\-|\\]", 
           convert = TRUE, 
           extra = "drop") %>% 
  rename(country = Location) %>% 
  mutate(country = case_when(
    country == "Bolivia (Plurinational State of)" ~ "Bolivia",
    country == "Venezuela (Bolivarian Republic of)" ~ "Venezuela",
    TRUE ~ country
  ))

write.csv(e60, paste0(out_dir,"../e60.csv"))

#infant mortality rates
ifr_path <- paste0(data_dir, "IMR")
ifr_files <- list.files(path = ifr_path, pattern = "*.csv", full.names = TRUE, ignore.case = TRUE)

ifr_dfs <- lapply(ifr_files, function(file) {
  tryCatch({
    read_csv(file, col_types = cols(.default = "c"))  # Read all columns as character initially
  }, error = function(e) {
    warning(paste("Error reading file:", file, "-", e$message))
    return(NULL)
  })
})

names(ifr_dfs) <- basename(ifr_files)
ifr_dfs <- ifr_dfs[!sapply(ifr_dfs, is.null)]  # Remove any NULL entries (failed reads)

ifr_dfs <- lapply(names(ifr_dfs), function(name) {
  tryCatch({
    df <- ifr_dfs[[name]]
    df %>% 
      mutate(
        df_name = name,
        Int. = as.numeric(as.character(ifelse(Int. %in% c("N/A", "-"), NA, Int.))),
        `Ref. date` = as.numeric(`Ref. date`)
      ) %>% 
      filter(`Ref. date` %in% c(1950, 2010, 2019))
  }, error = function(e) {
    message(paste("Error in processing file:", name))
    message("Error message:", e$message)
    return(NULL)  # Return NULL for this iteration if there's an error
  })
})

ifr_df <- bind_rows(ifr_dfs) %>% 
  filter(!is.na(`Std. err`) & !Name %in% c("Census 2010 (Household Deaths)", "Demographic and Health Survey 2013 (Direct)", "VR from Oficina Nacional de Estadistica 2021 (VR)", "Encuesta Nacional de la Dinamica Demografica (ENADID) 2018 (Direct)", "Vital Registration data from Mexico Ministry of Health 2018 (VR)")) %>% 
  mutate(country = case_when(
      #df_name == "PRI-Infant mortality rate-Total-datasources-download.csv" ~ "Puerto Rico",
      df_name == "CAN-Infant mortality rate-Total-datasources-download.csv" ~ "Canada",
      df_name == "MEX-Infant mortality rate-Total-datasources-download.csv" ~ "Mexico",
      df_name == "BLZ-Infant mortality rate-Total-datasources-download.csv" ~ "Belize",
      df_name == "CRI-Infant mortality rate-Total-datasources-download.csv" ~ "Costa Rica",
      df_name == "SLV-Infant mortality rate-Total-datasources-download.csv" ~ "El Salvador",
      df_name == "GTM-Infant mortality rate-Total-datasources-download.csv" ~ "Guatemala",
      df_name == "HND-Infant mortality rate-Total-datasources-download.csv" ~ "Honduras",
      df_name == "NIC-Infant mortality rate-Total-datasources-download.csv" ~ "Nicaragua",
      df_name == "PAN-Infant mortality rate-Total-datasources-download.csv" ~ "Panama",
      df_name == "CUB-Infant mortality rate-Total-datasources-download.csv" ~ "Cuba",
      df_name == "DOM-Infant mortality rate-Total-datasources-download.csv" ~ "Dominican Republic",
      df_name == "HTI-Infant mortality rate-Total-datasources-download.csv" ~ "Haiti",
      df_name == "JAM-Infant mortality rate-Total-datasources-download.csv" ~ "Jamaica",
      df_name == "DMA-Infant mortality rate-Total-datasources-download.csv" ~ "Dominica",
      df_name == "TTO-Infant mortality rate-Total-datasources-download.csv" ~ "Trinidad and Tobago",
      df_name == "ARG-Infant mortality rate-Total-datasources-download.csv" ~ "Argentina",
      df_name == "BOL-Infant mortality rate-Total-datasources-download.csv" ~ "Bolivia",
      df_name == "BRA-Infant mortality rate-Total-datasources-download.csv" ~ "Brazil",
      df_name == "CHL-Infant mortality rate-Total-datasources-download.csv" ~ "Chile",
      df_name == "COL-Infant mortality rate-Total-datasources-download.csv" ~ "Colombia",
      df_name == "ECU-Infant mortality rate-Total-datasources-download.csv" ~ "Ecuador",
      df_name == "GUY-Infant mortality rate-Total-datasources-download.csv" ~ "Guyana",
      df_name == "PRY-Infant mortality rate-Total-datasources-download.csv" ~ "Paraguay",
      df_name == "PER-Infant mortality rate-Total-datasources-download.csv" ~ "Peru",
      df_name == "URY-Infant mortality rate-Total-datasources-download.csv" ~ "Uruguay",
      df_name == "VEN-Infant mortality rate-Total-datasources-download.csv" ~ "Venezuela",
      TRUE ~ "Unknown"  # This will catch any unmatched file names
    )) %>% 
  select(Value, `Ref. date`, country) %>%
  mutate(Value = as.character(Value)) %>%
  add_row(Value = "6.861", `Ref. date` = 2010, country = "Puerto Rico") %>% 
  add_row(Value = "70.531", `Ref. date` = 1950, country = "Puerto Rico") %>% 
  add_row(Value = "5.309", `Ref. date` = 2019, country = "Puerto Rico") %>%
  add_row(Value = "87.121", `Ref. date` = 1950, country = "Cuba") %>% 
  rename(ifr = Value,
         ifr_year = `Ref. date`) %>% 
  slice(-2)


rm(ifr_path, ifr_files)

ifr_2010 <- ifr_df %>% 
  filter(ifr_year == 2010) %>% 
  rename(ifr_2010 = ifr) %>% 
  select(-ifr_year)

ifr_1950 <- ifr_df %>% 
  filter(ifr_year == 1950) %>% 
  rename(ifr_1950 = ifr) %>% 
  select(-ifr_year)

ifr_2019 <- ifr_df %>% 
  filter(ifr_year == 2019) %>% 
  rename(ifr_2019 = ifr) %>% 
  select(-ifr_year)

#merging all background data into one df
background_data <- left_join(e60, gdp, by = "country")
background_data <- left_join(background_data, ifr_2010, by = "country")
background_data <- left_join(background_data, ifr_1950, by = "country")
background_data <- left_join(background_data, ifr_2019, by = "country")


background_data <- background_data %>%
  arrange(desc(ifr_2010)) %>%
  distinct(country, .keep_all = TRUE)

counts <- read.csv(paste0(data_dir,"hispanic_immigrant_count.csv")) %>% 
  select(bpld_string, count, percent) %>% 
  mutate(percent = percent*100) %>% 
  rename(country = bpld_string)

background_data <- left_join(background_data, counts, by = "country") %>% 
  arrange(country)

rm(ifr_2010, ifr_1950, ifr_2019, ifr_df, ifr_dfs, gdp, e60)

write.csv(background_data, paste0(out_dir,"../background_data.csv"))
```
## table on background features
```{r}
background_table <- background_data %>% 
  select(country, gdp, e60, ifr_1950, ifr_2010) %>% 
  rename(Country = country,
         `2010 GDP` = gdp,
         `Life Expectancy at 60` = e60,
         `Infant Mortality Rate (1950)` = ifr_1950,
         `Infant Mortality Rate (2010)` = ifr_2010
  )

print(background_table)
```
## table1
```{r}
table1<- us_df_2020 %>%
    filter(country_string == "mexico" | 
       country_string == "puerto rico" | 
       country_string == "dominican republic" |
       country_string == "cuba") %>% 
    group_by(country_string) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    ))

print(table1)

table1_migrant <- us_df_2020 %>%
  filter(!country_string %in% c("mexico", "puerto rico", "dominican republic", "cuba")) %>% 
  filter(!hispanic_category_migrant_status %in% c("native-born Not Latino")) %>% 
    group_by(hispanic_category_migrant_status) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -hispanic_category_migrant_status, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = hispanic_category_migrant_status, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable)

print(table1_migrant)

table1_native_race <- us_df_2020 %>%
  filter(race_native_category %in% c(10, 11, 12)) %>% 
    group_by(race_native_category) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -race_native_category, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = race_native_category, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable) %>% 
  rename(`Black` = `10`,
         `White` = `11`,
         `Other` = `12`)

print(table1_native_race)

table1 <- bind_cols(
  table1,
  table1_migrant,
  table1_native_race
)

rm(table1_migrant, table1_native_race)

table1 <- table1 %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  select(variable, mexico, `puerto rico`, `dominican republic`, cuba,`foreign-born Central-American Latino`, `foreign-born Other Latino`,`foreign-born Not Latino`, `native-born Other Latino`, `Black`, `White`, `Other`) %>% 
  rename(
    `Dominican Republic` = `dominican republic`,
    Mexico = mexico,
    `Puerto Rico` = `puerto rico`,
    Demographics = variable,
    Cuba = cuba,
    `Central America` = `foreign-born Central-American Latino`,
    `Latin America` = `foreign-born Other Latino`,
    `Other Countries` = `foreign-born Not Latino`,
    `Hispanic` = `native-born Other Latino`
  ) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 6) %>% 
  add_row(Demographics = "Household", .before = 11) %>% 
  add_row(Demographics = "Age Migrated", .before = 16) %>% 
  add_row(Demographics = "Migration Cohort", .before = 21) %>% 
  add_row(Demographics = "Acculturation", .before = 26)

print(table1)

table1_code <- xtable(table1, 
                                   caption = "Sociodemographics of Hispanics in the U.S. by Birth Country (2020 Census)", 
                                   align = "ll|ccccccccccc")

latex_code <- capture.output(print(table1_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

#to replace align tabular code
tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{3.2cm}|lcccccc|cccc}"

# To align rows right
adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89", "90 plus"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("50 and Above"), width = 2.6),
  list(rows = c("15 - 23", "24 - 49", "Citizen"), width = 1.6),
  list(rows = c("Lives with Child"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999", "Lives Alone"), width = 2.2),
  list(rows = c("After 1999"), width = 2.1),
  list(rows = c("Household Size"), width = 2.7),
  list(rows = c("English Speakers"), width = 3.0),
  list(rows = c("Married/Cohabiting"), width = 3.4)
)

adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    for (row in adjustment$rows) {
      row_index <- grep(paste0("^\\s*", row), latex_code)
      if (length(row_index) > 0) {
        latex_code[row_index] <- gsub(
          "^(\\s*)(.*?)(&.*)",
          sprintf("\\1\\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{%scm}|}{\\\\makebox[%scm][r]{\\2}}\\3",
                  adjustment$width, adjustment$width),
          latex_code[row_index]
        )
      }
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table1.tex")

rm(table1, table1_code, adjustments, latex_code, adjust_latex_rows)
```
## table2, featuring Hispanic in their native countries
```{r}
create_table_for_sex_international <- function(sex_value) {
  in_df %>%
    filter(sex == sex_value) %>%
    filter(!is.na(country_string)) %>% 
    group_by(country_string) %>%
    summarise(
    mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
    mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
    mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
    mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
    mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
    mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
    mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
    mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
    mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
    mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
    mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
    mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
    N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University"
    ))
}

table1_sex_1 <- create_table_for_sex_international(1)
table1_sex_2 <- create_table_for_sex_international(2)

combined_table1 <- bind_rows(
  table1_sex_2, #females first
  table1_sex_1 #males second
)

combined_table1 <- combined_table1 %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  rename(Demographics = variable)

#adding in the US born counterparts
create_table_for_sex_us_counterparts <- function(sex_value) {
  us_df_2010 %>%
    filter(sex == sex_value) %>%
    filter(country_string %in% c("mexico", "dominican republic", "cuba", "puerto rico")) %>% 
    group_by(country_string) %>%
    summarise(
    mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
    mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
    mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
    mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
    mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
    mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
    mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
    mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
    mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
    mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
    mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
    mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
    N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University"
    ))
}

table1_sex_1_us <- create_table_for_sex_us_counterparts(1)
table1_sex_2_us <- create_table_for_sex_us_counterparts(2)

combined_table2 <- bind_rows(
  table1_sex_2_us, #females first
  table1_sex_1_us #males second
)

combined_table2 <- combined_table2 %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  select(-variable) 

table1 <- cbind(combined_table1, combined_table2) %>% 
  rename(`US Mexican-born` = mexico,
         `US Puerto-Rican-born` = `puerto rico`,
         `US Dominican-born` = `dominican republic`,
         `US Cuban-born` = cuba,
         `Cubans`  = Cuba,
         `Dominicans`  = DR,
         `Mexicans`  = Mexico,
         `Puerto Ricans`  = PR,
         `All US Residents` = US
         ) %>%
  select(
    Demographics,
    `Mexicans`, `US Mexican-born`, 
    `Puerto Ricans`, `US Puerto-Rican-born`,
    `Dominicans`, `US Dominican-born`,
    `Cubans`, `US Cuban-born`
  ) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 6) %>% 
  add_row(Demographics = "Household", .before = 11) %>% 
  add_row(Demographics = "Age", .before = 17) %>% 
  add_row(Demographics = "Education Completed", .before = 22) %>% 
  add_row(Demographics = "Household", .before = 27) %>% 
  mutate(Gender = ifelse(row_number() == 1, "Female", 
                         ifelse(row_number() == 17, "Male", ""))) %>%
  select(Gender, everything())

print(table1)

table1_code <- xtable(table1, 
                                   caption = "Summary Statistics by Country and Sex For Hispanics in Their Native Countries", 
                                   align = "lll|cccccccc")

latex_code <- capture.output(print(table1_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{l>{\\raggedright\\arraybackslash}p{3.2cm}|ccccccccc}"

adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89", "90 plus"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("50 and Above", "Citizen"), width = 2.6),
  list(rows = c("15 - 23", "24 - 49"), width = 1.6),
  list(rows = c("Lives with Child"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999", "Lives Alone"), width = 2.2),
  list(rows = c("After 1999"), width = 2.1),
  list(rows = c("Household Size"), width = 2.7),
  list(rows = c("English Speakers"), width = 3.0),
  list(rows = c("Married/Cohabiting"), width = 3.4)
)

# Function to adjust LaTeX rows based on the adjustments list
adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    width <- adjustment$width
    for (row in adjustment$rows) {
      pattern <- paste0("(?<=[&|])\\s*", row, "(?=\\s*[&|])")
      replacement <- paste0(" \\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{", width, "cm}|}{\\\\makebox[", width, "cm][r]{", row, " }}")
      latex_code <- gsub(pattern, replacement, latex_code, perl = TRUE)
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)
print(latex_code)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table2.tex")
```

## Append table 1, race categories
```{r}
variable_labels <- c(
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_married_cohab = "Married/Cohabiting",
      mean_female = "Female",
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to49 = "15 - 49",
      mean_age_at_immigration_50plus = "Greater than 50",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 2000"
)

table3_consolidated <- us_df_2020 %>%
    filter(!is.na(hispanic_migrant_status_race)) %>% 
    filter(!str_detect(hispanic_migrant_status_race, "not")) %>% 
    group_by(hispanic_migrant_status_race) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to49 = weighted.mean(age_at_immigration_15to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_citizen, perwt, na.rm = TRUE),
      mean_female = weighted.mean(female, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -hispanic_migrant_status_race, names_to = "Demographics", values_to = "value") %>%
    pivot_wider(names_from = hispanic_migrant_status_race, values_from = value) %>%
    mutate(Demographics = Demographics %>% 
             recode(!!!variable_labels))

table3_consolidated <-table3_consolidated %>% 
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 5) %>% 
  add_row(Demographics = "Migrated", .before = 11) %>% 
  add_row(Demographics = "Migration Cohort", .before = 15) %>% 
  rename(`Foreign Black Hispanic` = `foreign-born black hispanic`,
         `Foreign White Hispanic` = `foreign-born white hispanic`,
         `Foreign Other Hispanic` = `foreign-born other hispanic`,
         `Native White Hispanic` = `native-born white hispanic`,
         `Native Black Hispanic` = `native-born black hispanic`,
         `Native Other Hispanic` = `native-born other hispanic`) %>% 
  select(Demographics,
         `Foreign Black Hispanic`, `Foreign White Hispanic`, `Foreign Other Hispanic`,
         `Native Black Hispanic`, `Native White Hispanic`, `Native Other Hispanic`)
  
print(table3_consolidated)

colnames(table3_consolidated) <- c("Demographics", 
                                   "Black Hispanic", "White Hispanic", "Other Hispanic",
                                   "Black Hispanic", "White Hispanic", "Other Hispanic")

table3_consolidated_code <- xtable(table3_consolidated, 
                                   caption = "Sociodemographics of Hispanics in the U.S. by Birth Race (2020 Census)", 
                                   align = "ll|cccccc")

# Generate LaTeX code
latex_code <- capture.output(print(table3_consolidated_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

# Find the position of the header row
header_pos <- which(grepl("Demographics & Black Hispanic", latex_code))

if (length(header_pos) > 0) {
  # Insert the new rows with labels
  new_rows <- c(
    "  & \\multicolumn{3}{c|}{Foreign Born} & \\multicolumn{3}{c}{Native Born} \\\\",
    "\\cline{2-7}"
  )
  latex_code <- c(latex_code[1:(header_pos-1)], 
                  new_rows,
                  latex_code[header_pos:length(latex_code)])
} else {
  warning("Could not find the header row in the LaTeX code.")
}

#to replace align tabular code
tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{3.2cm}|cccccc}"

# To align rows right
adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("15 - 49"), width = 1.6),
  list(rows = c("Greater than 50"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999"), width = 2.2),
  list(rows = c("After 2000"), width = 2.1)
)

adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    for (row in adjustment$rows) {
      row_index <- grep(paste0("^\\s*", row), latex_code)
      if (length(row_index) > 0) {
        latex_code[row_index] <- gsub(
          "^(\\s*)(.*?)(&.*)",
          sprintf("\\1\\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{%scm}|}{\\\\makebox[%scm][r]{\\2}}\\3",
                  adjustment$width, adjustment$width),
          latex_code[row_index]
        )
      }
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table3_consolidated.tex")
```

## append table 2, preoportion that speak english
```{r}
countries <- c("mexico", "puerto rico", "dominican republic", "cuba")

result_list <- list()

for (country in countries) {
  prop_cohort_speaks_english_country <- us_df_2020 %>% 
    filter(country_string == country) %>%
    group_by(age_groups) %>% 
    summarise(
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE)
    )
  
  # Store the result in the list
  result_list[[country]] <- prop_cohort_speaks_english_country$mean_english_speaker
}

prop_cohort_speaks_english <- data.frame(
  age_groups = prop_cohort_speaks_english_country$age_groups,
  do.call(cbind, result_list)
) %>% 
  mutate(age_groups = case_when(
    age_groups == 1 ~ "60 - 69",
    age_groups == 2 ~ "70 - 79",
    age_groups == 3 ~ "80 - 89"
  ))

print(prop_cohort_speaks_english)
```
## append table 3, proportion of cohort that speak english
```{r}
result_list <- list()

for (country in countries) {
  prop_cohort_speaks_english_country <- us_df_2020 %>% 
    filter(country_string == country) %>%
    group_by(year_of_immigration_groups) %>% 
    summarise(
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE)
    )
  
  result_list[[country]] <- prop_cohort_speaks_english_country$mean_english_speaker
}

prop_migration_cohort_speaks_english <- data.frame(
  year_of_immigration_groups = prop_cohort_speaks_english_country$year_of_immigration_groups,
  do.call(cbind, result_list)
) %>% 
  mutate(year_of_immigration_groups = case_when(
    year_of_immigration_groups == 1 ~ "Before 1965",
    year_of_immigration_groups == 2 ~ "1965 - 1979",
    year_of_immigration_groups == 3 ~ "1980 - 1999",
    year_of_immigration_groups == 4 ~ "After 1999",
  )) %>%
  mutate(year_of_immigration_groups = factor(year_of_immigration_groups, 
                                             levels = c("Before 1965", "1965 - 1979", "1980 - 1999", "After 1999")))

print(prop_migration_cohort_speaks_english)
```
# append table 4, table 1 but using 2010 data
```{r}
table1_2010<- us_df_2010 %>%
    filter(country_string == "mexico" | 
       country_string == "puerto rico" | 
       country_string == "dominican republic" |
       country_string == "cuba") %>% 
    group_by(country_string) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    ))

print(table2_consolidated)

table2_consolidated_migrant <- us_df_2010 %>%
  filter(!country_string %in% c("mexico", "puerto rico", "dominican republic", "cuba")) %>% 
  filter(!hispanic_category_migrant_status %in% c("native-born Not Latino")) %>% 
    group_by(hispanic_category_migrant_status) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -hispanic_category_migrant_status, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = hispanic_category_migrant_status, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable)

print(table2_consolidated_migrant)

table2_consolidated_native_race <- us_df_2010 %>%
  filter(race_native_category %in% c(10, 11, 12)) %>% 
    group_by(race_native_category) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -race_native_category, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = race_native_category, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable) %>% 
  rename(`Black` = `10`,
         `White` = `11`,
         `Other` = `12`)

print(table2_consolidated_native_race)

table1_2010<- bind_cols(
  table2_consolidated,
  table2_consolidated_migrant,
  table2_consolidated_native_race
)

rm(table2_consolidated_migrant, table2_consolidated_native_race)

table1_2010<- table1_2010%>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  select(variable, mexico, `puerto rico`, `dominican republic`, cuba,`foreign-born Central-American Latino`, `foreign-born Other Latin-American`,`foreign-born Not Latino`, `native-born Other Latin-American`, `Black`, `White`, `Other`) %>% 
  rename(
    `Dominican Republic` = `dominican republic`,
    Mexico = mexico,
    `Puerto Rico` = `puerto rico`,
    Demographics = variable,
    Cuba = cuba,
    `Central America` = `foreign-born Central-American Latino`,
    `Latin America` = `foreign-born Other Latin-American`,
    `Other` = `foreign-born Not Latino`,
    `Hispanic` = `native-born Other Latin-American`
  ) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 6) %>% 
  add_row(Demographics = "Household", .before = 11) %>% 
  add_row(Demographics = "Age Migrated", .before = 16) %>% 
  add_row(Demographics = "Migration Cohort", .before = 21) %>% 
  add_row(Demographics = "Acculturation", .before = 26)

print(table2_consolidated)

table2_consolidated_code <- xtable(table2_consolidated, 
                                   caption = "Sociodemographics of Hispanics in the U.S. by Birth Country (2006-10 ACS)", 
                                   align = "ll|ccccccccccc")

latex_code <- capture.output(print(table2_consolidated_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

#to replace align tabular code
tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{3.2cm}|lcccccc|cccc}"

# To align rows right
adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89", "90 plus"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("50 and Above"), width = 2.6),
  list(rows = c("15 - 23", "24 - 49", "Citizen"), width = 1.6),
  list(rows = c("Lives with Child"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999", "Lives Alone"), width = 2.2),
  list(rows = c("After 1999"), width = 2.1),
  list(rows = c("Household Size"), width = 2.7),
  list(rows = c("English Speakers"), width = 3.0),
  list(rows = c("Married/Cohabiting"), width = 3.4)
)

adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    for (row in adjustment$rows) {
      row_index <- grep(paste0("^\\s*", row), latex_code)
      if (length(row_index) > 0) {
        latex_code[row_index] <- gsub(
          "^(\\s*)(.*?)(&.*)",
          sprintf("\\1\\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{%scm}|}{\\\\makebox[%scm][r]{\\2}}\\3",
                  adjustment$width, adjustment$width),
          latex_code[row_index]
        )
      }
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table1_2010.tex")
```

# append table 1 but only female
```{r}
table2_consolidated_female <- us_df_2020 %>%
    filter(country_string == "mexico" | 
       country_string == "puerto rico" | 
       country_string == "dominican republic" |
       country_string == "cuba",
       female == 1) %>% 
    group_by(country_string) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    ))

print(table2_consolidated_female)

table2_consolidated_female_migrant <- us_df_2020 %>%
  filter(!country_string %in% c("mexico", "puerto rico", "dominican republic", "cuba")) %>% 
  filter(!hispanic_category_migrant_status %in% c("native-born Not Latino"),
         female == 1) %>% 
    group_by(hispanic_category_migrant_status) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -hispanic_category_migrant_status, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = hispanic_category_migrant_status, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable)

print(table2_consolidated_female_migrant)

table2_consolidated_female_native_race <- us_df_2020 %>%
  filter(race_native_category %in% c(10, 11, 12),
         female == 1) %>% 
    group_by(race_native_category) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -race_native_category, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = race_native_category, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable) %>% 
  rename(`Black` = `10`,
         `White` = `11`,
         `Other` = `12`)

print(table2_consolidated_female_native_race)

table2_consolidated_female <- bind_cols(
  table2_consolidated_female,
  table2_consolidated_female_migrant,
  table2_consolidated_female_native_race
)

rm(table2_consolidated_female_migrant, table2_consolidated_female_native_race)

table2_consolidated_female <- table2_consolidated_female %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  select(variable, mexico, `puerto rico`, `dominican republic`, cuba,`foreign-born Central-American Latino`, `foreign-born Other Latin-American`,`foreign-born Not Latino`, `native-born Other Latin-American`, `Black`, `White`, `Other`) %>% 
  rename(
    `Dominican Republic` = `dominican republic`,
    Mexico = mexico,
    `Puerto Rico` = `puerto rico`,
    Demographics = variable,
    Cuba = cuba,
    `Central America` = `foreign-born Central-American Latino`,
    `Latin America` = `foreign-born Other Latin-American`,
    `Other` = `foreign-born Not Latino`,
    `Hispanic` = `native-born Other Latin-American`
  ) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 6) %>% 
  add_row(Demographics = "Household", .before = 11) %>% 
  add_row(Demographics = "Age Migrated", .before = 16) %>% 
  add_row(Demographics = "Migration Cohort", .before = 21) %>% 
  add_row(Demographics = "Acculturation", .before = 26)

print(table2_consolidated_female)

table2_consolidated_female_code <- xtable(table2_consolidated_female, 
                                   caption = "Sociodemographics of Female Hispanics in the U.S. by Birth Country (2020 Census)", 
                                   align = "ll|ccccccccccc")

latex_code <- capture.output(print(table2_consolidated_female_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

#to replace align tabular code
tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{3.2cm}|lcccccc|cccc}"

# To align rows right
adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89", "90 plus"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("50 and Above"), width = 2.6),
  list(rows = c("15 - 23", "24 - 49", "Citizen"), width = 1.6),
  list(rows = c("Lives with Child"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999", "Lives Alone"), width = 2.2),
  list(rows = c("After 1999"), width = 2.1),
  list(rows = c("Household Size"), width = 2.7),
  list(rows = c("English Speakers"), width = 3.0),
  list(rows = c("Married/Cohabiting"), width = 3.4)
)

adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    for (row in adjustment$rows) {
      row_index <- grep(paste0("^\\s*", row), latex_code)
      if (length(row_index) > 0) {
        latex_code[row_index] <- gsub(
          "^(\\s*)(.*?)(&.*)",
          sprintf("\\1\\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{%scm}|}{\\\\makebox[%scm][r]{\\2}}\\3",
                  adjustment$width, adjustment$width),
          latex_code[row_index]
        )
      }
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table1_female.tex")
```
#append, table 1 but only males
```{r}
table2_consolidated_male <- us_df_2020 %>%
    filter(country_string == "mexico" | 
       country_string == "puerto rico" | 
       country_string == "dominican republic" |
       country_string == "cuba",
       male == 1) %>% 
    group_by(country_string) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    ))

print(table2_consolidated_male)

table2_consolidated_male_migrant <- us_df_2020 %>%
  filter(!country_string %in% c("mexico", "puerto rico", "dominican republic", "cuba")) %>% 
  filter(!hispanic_category_migrant_status %in% c("native-born Not Latino"),
         male == 1) %>% 
    group_by(hispanic_category_migrant_status) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -hispanic_category_migrant_status, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = hispanic_category_migrant_status, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable)

print(table2_consolidated_male_migrant)

table2_consolidated_male_native_race <- us_df_2020 %>%
  filter(race_native_category %in% c(10, 11, 12),
         male == 1) %>% 
    group_by(race_native_category) %>%
    summarise(
      mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
      mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
      mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
      mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
      mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
      mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
      mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
      mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
      mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
      mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
      mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
      mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
      mean_age_at_immigration_15 = weighted.mean(age_at_immigration_under15, perwt, na.rm = TRUE),
      mean_age_at_immigration_15to24 = weighted.mean(age_at_immigration_15to24, perwt, na.rm = TRUE),
      mean_age_at_immigration_25to49 = weighted.mean(age_at_immigration_25to49, perwt, na.rm = TRUE),
      mean_age_at_immigration_50plus = weighted.mean(age_at_immigration_50plus, perwt, na.rm = TRUE),
      mean_yrimm_before1965 = weighted.mean(yrimm_before1965, perwt, na.rm = TRUE),
      mean_yrimm_1965_1979 = weighted.mean(yrimm_1965to1980, perwt, na.rm = TRUE),
      mean_yrimm_1980_1999 = weighted.mean(yrimm_1980to1999, perwt, na.rm = TRUE),
      mean_yrimm_2000plus = weighted.mean(yrimm_2000plus, perwt, na.rm = TRUE),
      mean_is_citizen = weighted.mean(is_naturalized_citizen, perwt, na.rm = TRUE),
      mean_english_speaker = weighted.mean(english_speaker, perwt, na.rm = TRUE),
      N = n()
    ) %>%
    pivot_longer(cols = -race_native_category, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = race_native_category, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_english_speaker = "English Speakers",
      mean_is_citizen = "Citizen",
      mean_age_at_immigration_15 = "Less than 15",
      mean_age_at_immigration_15to24 = "15 - 23",
      mean_age_at_immigration_25to49 = "24 - 49",
      mean_age_at_immigration_50plus = "50 and Above",
      mean_years_in_us = "Years in US",
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University",
      mean_yrimm_before1965 = "Before 1965",
      mean_yrimm_1965_1979 = "1965 - 1979",
      mean_yrimm_1980_1999 = "1980 - 1999",
      mean_yrimm_2000plus = "After 1999"
    )) %>% 
    select(-variable) %>% 
  rename(`Black` = `10`,
         `White` = `11`,
         `Other` = `12`)

print(table2_consolidated_male_native_race)

table2_consolidated_male <- bind_cols(
  table2_consolidated_male,
  table2_consolidated_male_migrant,
  table2_consolidated_male_native_race
)

rm(table2_consolidated_male_migrant, table2_consolidated_male_native_race)

table2_consolidated_male <- table2_consolidated_male %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  select(variable, mexico, `puerto rico`, `dominican republic`, cuba,`foreign-born Central-American Latino`, `foreign-born Other Latin-American`,`foreign-born Not Latino`, `native-born Other Latin-American`, `Black`, `White`, `Other`) %>% 
  rename(
    `Dominican Republic` = `dominican republic`,
    Mexico = mexico,
    `Puerto Rico` = `puerto rico`,
    Demographics = variable,
    Cuba = cuba,
    `Central America` = `foreign-born Central-American Latino`,
    `Latin America` = `foreign-born Other Latin-American`,
    `Other` = `foreign-born Not Latino`,
    `Hispanic` = `native-born Other Latin-American`
  ) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 6) %>% 
  add_row(Demographics = "Household", .before = 11) %>% 
  add_row(Demographics = "Age Migrated", .before = 16) %>% 
  add_row(Demographics = "Migration Cohort", .before = 21) %>% 
  add_row(Demographics = "Acculturation", .before = 26)

print(table2_consolidated_male)

table2_consolidated_male_code <- xtable(table2_consolidated_male, 
                                   caption = "Sociodemographics of Male Hispanics in the U.S. by Birth Country (2020 Census)", 
                                   align = "ll|ccccccccccc")

latex_code <- capture.output(print(table2_consolidated_male_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

#to replace align tabular code
tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{3.2cm}|lcccccc|cccc}"

# To align rows right
adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89", "90 plus"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("50 and Above"), width = 2.6),
  list(rows = c("15 - 23", "24 - 49", "Citizen"), width = 1.6),
  list(rows = c("Lives with Child"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999", "Lives Alone"), width = 2.2),
  list(rows = c("After 1999"), width = 2.1),
  list(rows = c("Household Size"), width = 2.7),
  list(rows = c("English Speakers"), width = 3.0),
  list(rows = c("Married/Cohabiting"), width = 3.4)
)

adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    for (row in adjustment$rows) {
      row_index <- grep(paste0("^\\s*", row), latex_code)
      if (length(row_index) > 0) {
        latex_code[row_index] <- gsub(
          "^(\\s*)(.*?)(&.*)",
          sprintf("\\1\\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{%scm}|}{\\\\makebox[%scm][r]{\\2}}\\3",
                  adjustment$width, adjustment$width),
          latex_code[row_index]
        )
      }
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table1_male.tex")
```
# append, table 2 but age standardized
```{r}
create_table_for_sex_international_standardized <- function(sex_value) {
  in_df %>%
    filter(sex == sex_value) %>%
    filter(!is.na(country_string)) %>% 
    group_by(country_string) %>%
    summarise(
    mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
    mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
    mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
    mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
    mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt_age_standardized, na.rm = TRUE),
    mean_primary_completed = weighted.mean(primary_completed, perwt_age_standardized, na.rm = TRUE),
    mean_secondary_completed = weighted.mean(secondary_completed, perwt_age_standardized, na.rm = TRUE),
    mean_university_completed = weighted.mean(university_completed, perwt_age_standardized, na.rm = TRUE),
    mean_hhsize = weighted.mean(famsize, perwt_age_standardized, na.rm = TRUE),
    mean_lives_alone = weighted.mean(lives_alone, perwt_age_standardized, na.rm = TRUE),
    mean_has_child_in_hh = weighted.mean(child_in_household, perwt_age_standardized, na.rm = TRUE),
    mean_married_cohab = weighted.mean(married_cohab, perwt_age_standardized, na.rm = TRUE),
    N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University"
    ))
}

table1_sex_1 <- create_table_for_sex_international_standardized(1)
table1_sex_2 <- create_table_for_sex_international_standardized(2)

combined_table1 <- bind_rows(
  table1_sex_2, #females first
  table1_sex_1 #males second
)

combined_table1 <- combined_table1 %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  rename(Demographics = variable)

#adding in the US born counterparts
create_table_for_sex_us_counterparts <- function(sex_value) {
  us_df_2010 %>%
    filter(sex == sex_value) %>%
    filter(country_string %in% c("mexico", "dominican republic", "cuba", "puerto rico")) %>% 
    group_by(country_string) %>%
    summarise(
    mean_age_60_69 = weighted.mean(age_60to69, perwt, na.rm = TRUE),
    mean_age_70_79 = weighted.mean(age_70to79, perwt, na.rm = TRUE),
    mean_age_80_89 = weighted.mean(age_80to89, perwt, na.rm = TRUE),
    mean_age_90plus = weighted.mean(age_90plus, perwt, na.rm = TRUE), 
    mean_less_than_primary_completed = weighted.mean(less_than_primary_completed, perwt, na.rm = TRUE),
    mean_primary_completed = weighted.mean(primary_completed, perwt, na.rm = TRUE),
    mean_secondary_completed = weighted.mean(secondary_completed, perwt, na.rm = TRUE),
    mean_university_completed = weighted.mean(university_completed, perwt, na.rm = TRUE),
    mean_hhsize = weighted.mean(famsize, perwt, na.rm = TRUE),
    mean_lives_alone = weighted.mean(lives_alone, perwt, na.rm = TRUE),
    mean_has_child_in_hh = weighted.mean(child_in_household, perwt, na.rm = TRUE),
    mean_married_cohab = weighted.mean(married_cohab, perwt, na.rm = TRUE),
    N = n()
    ) %>%
    pivot_longer(cols = -country_string, names_to = "variable", values_to = "value") %>%
    pivot_wider(names_from = country_string, values_from = value) %>%
    mutate(variable = recode(variable,
      mean_age_60_69 = "60 - 69",
      mean_age_70_79 = "70 - 79",
      mean_age_80_89 = "80 - 89",
      mean_age_90plus = "90 plus",
      mean_married_cohab = "Married/Cohabiting",
      mean_hhsize = "Household Size",
      mean_lives_alone = "Lives Alone",
      mean_has_child_in_hh = "Lives with Child", 
      mean_less_than_primary_completed = "Less than Primary",
      mean_primary_completed = "Primary",
      mean_secondary_completed = "Secondary",
      mean_university_completed = "University"
    ))
}

table1_sex_1_us <- create_table_for_sex_us_counterparts(1)
table1_sex_2_us <- create_table_for_sex_us_counterparts(2)

combined_table2 <- bind_rows(
  table1_sex_2_us, #females first
  table1_sex_1_us #males second
)

combined_table2 <- combined_table2 %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  mutate(across(everything(), ~ as.character(.))) %>%    
  mutate(across(everything(), ~ ifelse(. == "NaN", "-", .))) %>%   
  mutate(across(everything(), ~ ifelse(. == "0", "-", .))) %>% 
  select(-variable) 

table1_standardized <- cbind(combined_table1, combined_table2) %>% 
  rename(`US Mexican-born` = mexico,
         `US Puerto-Rican-born` = `puerto rico`,
         `US Dominican-born` = `dominican republic`,
         `US Cuban-born` = cuba,
         `Cubans`  = Cuba,
         `Dominicans`  = DR,
         `Mexicans`  = Mexico,
         `Puerto Ricans`  = PR,
         `All US Residents` = US
         ) %>%
  select(
    Demographics,
    `Mexicans`, `US Mexican-born`, 
    `Puerto Ricans`, `US Puerto-Rican-born`,
    `Dominicans`, `US Dominican-born`,
    `Cubans`, `US Cuban-born`
  ) %>% 
  add_row(Demographics = "Age", .before = 1) %>% 
  add_row(Demographics = "Education Completed", .before = 6) %>% 
  add_row(Demographics = "Household", .before = 11) %>% 
  add_row(Demographics = "Age", .before = 17) %>% 
  add_row(Demographics = "Education Completed", .before = 22) %>% 
  add_row(Demographics = "Household", .before = 27) %>% 
  mutate(Gender = ifelse(row_number() == 1, "Female", 
                         ifelse(row_number() == 17, "Male", ""))) %>%
  select(Gender, everything())

print(table1_standardized)

table1_code <- xtable(table1_standardized, 
                                   caption = "Summary Statistics by Country and Sex For Hispanics in Their Native Countries (Age Standardized)", 
                                   align = "lll|cccccccc")

latex_code <- capture.output(print(table1_code, 
                                   type = "latex", 
                                   caption.placement = "top",
                                   size = "\\small",
                                   include.rownames = FALSE))

tabular_line_index <- grep("\\\\begin\\{tabular\\}", latex_code)
latex_code[tabular_line_index] <- "\\begin{tabular}{l>{\\raggedright\\arraybackslash}p{3.2cm}|ccccccccc}"

adjustments <- list(
  list(rows = c("60 - 69", "70 - 79", "80 - 89", "90 plus"), width = 1.5),
  list(rows = c("Less than Primary"), width = 3.2),
  list(rows = c("Primary"), width = 1.7),
  list(rows = c("Secondary", "University"), width = 2),
  list(rows = c("Less than 15"), width = 2.4),
  list(rows = c("50 and Above", "Citizen"), width = 2.6),
  list(rows = c("15 - 23", "24 - 49"), width = 1.6),
  list(rows = c("Lives with Child"), width = 2.9),
  list(rows = c("Before 1965"), width = 2.3),
  list(rows = c("1965 - 1979", "1980 - 1999", "Lives Alone"), width = 2.2),
  list(rows = c("After 1999"), width = 2.1),
  list(rows = c("Household Size"), width = 2.7),
  list(rows = c("English Speakers"), width = 3.0),
  list(rows = c("Married/Cohabiting"), width = 3.4)
)

# Function to adjust LaTeX rows based on the adjustments list
adjust_latex_rows <- function(latex_code, adjustments) {
  for (adjustment in adjustments) {
    width <- adjustment$width
    for (row in adjustment$rows) {
      pattern <- paste0("(?<=[&|])\\s*", row, "(?=\\s*[&|])")
      replacement <- paste0(" \\\\multicolumn{1}{>{\\\\raggedleft\\\\arraybackslash}p{", width, "cm}|}{\\\\makebox[", width, "cm][r]{", row, " }}")
      latex_code <- gsub(pattern, replacement, latex_code, perl = TRUE)
    }
  }
  return(latex_code)
}

latex_code <- adjust_latex_rows(latex_code, adjustments)
print(latex_code)

writeLines(latex_code, "/Users/chrissoria/Documents/Research/us_international_ses/tables/r_tables/table2_standardized.tex")
```

