---
title: |
  Sociodemographic Comparison of Caribbean Hispanic Older Adult Immigrants in the U.S. and Origin Countries
format: 
  pdf:
    keep-tex: true
    documentclass: article
    latex-engine: xelatex
header-includes:
   - \usepackage{pdflscape}
   - \usepackage{caption}
   - \usepackage{booktabs}
   - \usepackage{threeparttable}
   - \usepackage{fancyhdr}
   - \usepackage{lastpage}
   - \usepackage{geometry}
   - \usepackage{array}
   - \usepackage{calc}
        
date: last-modified
tbl-cap-location: top
author:
  - name: William H. Dow
    affiliation: 1
  - name: Chris Soria
    affiliation: 1
  - name: Henry T. Dow
    affiliation: 1
affiliations:
  - name: University of California, Berkeley
    index: 1
      
abstract: |
  Caribbean and adjacent Latin American countries are key sources of Hispanic immigrants to the U.S. There has been rapid growth in the older adult Hispanic populations both among immigrants in the U.S. and in their home countries of emigration. This paper supports hypothesis generation for international comparative Hispanic aging studies by comparing older adult sociodemographic characteristics of U.S. immigrants versus those in sending countries. The analysis also provides context for the global family of health and retirement studies in the region including the ongoing Caribbean American Dementia and Aging Study (CADAS) which is collecting harmonized data on healthy aging in Puerto Rico, Dominican Republic, and Cuba. We analyze census microdata from these countries along with other major Hispanic Caribbean-adjacent sending countries including Mexico, Colombia, El Salvador, Guatemala, and Honduras. We compare older adults in these sending countries to country-specific immigrant samples in the U.S. American Community Survey, focusing on socioeconomic differences such as education, as well as marital status and co-residence patterns related to caregiver availability. We also examine differences by citizenship and immigration age to further explore immigrant selectivity patterns. The highly varied experiences of these cohorts will help inform future comparative research on Hispanic healthy aging.  
  
bibliography: usinternationalses.bib  
linestretch: 1.2
editor: 
  markdown: 
    wrap: 72
---

## Introduction and Background **TODO:** Rewrite this whole intro {#sec-intro}

In this paper we explore sociodemographic variation of U.S. older adult
immigrants by country and cohort of emigration, and compare these U.S.
immigrants to the corresponding cohorts of older adults in their home
countries of emigration.

The paper is designed to support hypothesis generation for international
comparative Hispanic aging studies. This includes providing background
context for the global family of health and retirement studies in the
region such as the ongoing Caribbean American Dementia and Aging Study
(CADAS) which is collecting harmonized data on healthy aging in Puerto
Rico, Dominican Republic, and Cuba
[@llibre-guerra_caribbean-american_2021]. We compare older adults in
these sending countries to country-specific immigrant samples in the
U.S. American Community Survey and Census, focusing on socioeconomic
differences such as education, as well as marital status and
co-residence patterns. We also examine differences by citizenship and
immigration age to further explore immigrant selectivity patterns. The
highly varied experiences of these cohorts will help inform future
comparative research on Hispanic healthy aging.

## Literature Review {#sec-lit}

Latin American and Caribbean Countries (LACCs) are key sources of
Hispanic immigrants to the United Sates [@passel_what_2024]. In 2022,
people of Mexican origin made up nearly 60% of the U.S. Hispanic
population, totaling about 37.4 million. Puerto Ricans were the next
largest group at 5.9 million, with an additional 3.2 million living on
the island. Salvadorans, Cubans, Dominicans, Guatemalans, Colombians,
and Hondurans each have populations exceeding 1 million in the United
States [@noe-bustamante_key_2023]. These immigrant populations include a
rapidly growing subgroup who are aged 60 and above, among whom there is
wide variation in socioeconomic and care giving resources.

These international migration patterns are shaped by a complex interplay
of factors, including labor market demands, educational opportunities,
and political and economic instability [@mcauliffe_who_2024;
@valentine_migration_2017]. In the North American context, Massey et al.
posit that established social networks play a pivotal role in migration
dynamics, with family reunification serving as a primary motivator
[@silva_violence_2014]. This reunification imperative creates a
self-perpetuating cycle of migration flows [@massey_evaluation_1994].
Age also significantly influences migration patterns, with younger
individuals typically dominating migrant populations. Mexican migrants
exemplify this trend; despite recent cohorts showing a slight increase
in average age, they remain predominantly youthful[@angel_aging_2017].
This persistent age pattern underscores migration's enduring appeal to
younger generations, even as sending countries' overall populations age
\[**TODO:** Will, do you know any good papers to cite here? Maybe an
HCAP paper?\].

Other LACCs similarly exhibit diverse migration drivers and patterns,
with specific political agreements further shaping these movements and
creating unique migration landscapes across the region. Puerto Rico's
special status as a U.S. territory since 1898, for instance, has
facilitated legal entry to the U.S. mainland for its residents[^1].
Likewise, the Cuban Adjustment Act of 1966 and subsequent policies, such
as the "wet foot, dry foot" policy (1995-2017), have significantly
influenced Cuban migration to the United States [@duany_cuban_2017].
These examples illustrate how political arrangements can create
facilitated migration channels, potentially leading to what migration
theorists term "migration systems" or "transnational social spaces"
[@kritz_international_1992].

[^1]: Despite their high out-migration rate, Puerto Ricans in the United
    States send less money than Dominicans and Mexicans to their
    relatives back home. Possible explanations for this are the
    extensive public support system in place on the island and
    relatively higher standard of living compared to other LACCs.
    [@duany_send_2010]

Economic factors underpin much of the migration from Latin America to
the United States, exemplifying classic push-pull migration theory
[@hanson_us_2023]. Economic insecurity in Latin American countries acts
as a push factor [@capielo_rosario_conceptualizing_2023;
@larotta_silva_determinantes_2019], while periods of US economic growth
further amplify wage differentials between the two regions
[@bahar_often_2024]. For instance, Colombian and Guatemalan workers in
the U.S. earn \$288-\$299 for every \$100 earned by their counterparts
at home, while Nicaraguan migrants see an even larger differential
[@clemens_place_2009][^2]. However, these wage differentials are
partially explained by positive selection, as migrants often possess
characteristics associated with higher productivity and adaptability.
This selection bias is further evidenced by research showing that
immigrants tend to have longer life expectancies than native-born
populations [@aldridge_global_2018].

[^2]: Beyond wages, housing availability [@henao_subjective_2023] and
    access to technology [@nevado-pena_improving_2019] significantly
    influence life satisfaction and migration decisions
    [@causa_should_2020; @winkler_how_2016]

Alongside economic factors, political instability has been a significant
driver of forced migration from Latin American countries to the United
States, aligning with theories of refugee and asylum migration
[@fitzgerald_sociology_2018]. Historical events underscore this trend.
The Cuban Revolution of 1959, for instance, generated the largest
refugee movement to the United States in history, resulting in
approximately 1.4 million Cuban refugees [@duany_cuban_2017][^3].
Similarly, the Salvadoran Civil War (1979-1992) led to the displacement
of about 1 million people, many of whom subsequently migrated to the
U.S., often through irregular channels [@cervantes_salvador_2018].
Guatemala and Honduras experienced similar trajectories of political
instability, exacerbated by U.S. interventions in the mid-20th century
[@jonas_centaurs_2018; @pine_working_2008]. These events led to
substantial emigration waves, with Guatemalan immigrants in the U.S.
increasing from 71,000 in 1980 to over 480,000 by 2000, and Honduran
immigrants from 39,000 to 283,000 [@batalova_central_2021]. Recent data
underscores this trend: in the first 11 months of 2023, over 50% of
approximately 412,000 asylum applications to the Department of Homeland
Security came from Venezuela, Cuba, Colombia, and Nicaragua
[@noauthor_nationwide_2024].

[^3]: This record was recently surpassed 2021-23
    [@gonzalez_current_2024]

Much of the literature on Latin American migrants predominantly focuses
on individuals who emigrated during periods of economic distress and
political upheaval. However, there is a notable paucity of research
examining those who opt to remain in their home countries under similar
circumstances. Additionally, there is a shortage of comparative studies
that analyze Latin American migrants in relation to both their
counterparts who stayed in their home countries and themselves prior to
migration, limiting our understanding of the full spectrum of migration
outcomes and selectivity. We addresses this gap by conducting a
comparative analysis of older adults from Latin American countries who
have migrated to the United States and their counterparts who have
remained in their countries of origin. By examining the sociodemographic
characteristics of these populations, this research aims to elucidate
the selectivity of migration processes and their long-term implications.

## Data and Methods {#sec-methods}

Census data for this study were obtained from IPUMS International
[@ruggles_ipums_2024]. The current analysis draws on the latest
harmonized census data available in IPUMS for Cuba (2012), the Dominican
Republic (2010), Mexico (2010;2020), Puerto Rico (2010;2020), and the
United States (2010; 2020)[^4]. We on individuals aged 60 and above,
grouping all people 90 and above into an open-ended category. **TODO:**
(should we keep this but refer to a table in the appendix?) To ensure
comparability, **we standardized means in the international censuses
based on the U.S. sex-specific age distribution. We also applied weights
provided by IPUMS to make the samples nationally representative.**

[^4]: PR 2010 is a 1% sample, PR 2020 is 5%, US 2010 is 1%, and US 2020
    is 5%. The 2010 and 2020 census data available through IPUMS
    International are limited to 1% and 5% samples, respectively. While
    the U.S. IPUMS database offers larger samples, it lacks certain
    variables, such as country of birth for the Dominican Republic.

To produce table 1, we utilize the total number of age 60+ migrants from
LACCs in the United States as of 2020 and their percentage of that
migration, GDP per capita as of 2019 [@noauthor_world_2025], Infant
Mortality Rates as of 1950 and 2019 [@noauthor_cme_2025;
@noauthor_world_2024], and life expectancy at 60
[@noauthor_global_2021].

When analyzing international censuses, we include variables age, percent
married/cohabiting, and highest educational level obtained (**TODO:**
using internationally standardized categorizations of less than primary,
primary, secondary, and university), household size, and sex. When
analyzing migrants in the US setting, we add additional variables on
whether the individual speaks English, is a naturalized citizen, and the
age and year they migrated to the US (see definitions in the appendix).

**TODO:** If we decide to keep predicted probabilities, should we
include a list of variables and model used to produce them?

## Results and Comparative Analysis {#sec-results}

**Table 1 observations:**

-   **Mexico has the highest percentage of migrants to the U.S. at
    43.99%.**

-   Haiti has the lowest percentage of migrants at 0.04%, indicating
    limited migration compared to other countries in the dataset.

-   **Our four countries of interest are the biggest migrant groups**

-   **Puerto Rico leads with a GDP per capita of \$36,779, which is much
    higher than other countries in the dataset.**

-   Haiti has the lowest GDP per capita at \$1,705

-   Haiti had an extremely high infant mortality rate of 237.19 deaths
    per 1,000 live births in 1950

-   Panama had the lowest rate in 1950 at 53.02 deaths per 1,000

-   Haiti remains the highest in 2019 with a rate of 53.03 deaths per
    1,000

-   **The Dominican Republic has the lowest infant mortality rate in
    2019 at just 4.14 deaths per 1,000**

-   Costa Rica (24.52 years) and Chile (24.57 years) have relatively
    high life expectancy at age 60

-   Haiti has the lowest life expectancy at age 60

-   **Of our four countries:**

    -   **Mexico contributes the largest number of migrants and has a
        relatively high GDP per capita (\$13,790) but also a higher
        infant mortality rate in 2019 (10.79) compared to countries like
        Cuba (4.89).**

    -   **The Dominican Republic has the lowest number of migrants (only
        6.04% of the total).**

    -   **Cuba has the lowest GDP per capita at \$9,605**

    -   **Mexico has the highest infant mortality rate**

    -   Cuba has the lowest life expectancy at age 60 (21.57 years) even
        though it has a relatively low IMR

-   Central American Countries:

    -   These countries have lower GDP per capita and higher infant
        mortality rates compared to South American countries.

**TODO:** Identify which migrant groups moved to the US at the youngest
ages comparatively Variations in migration motivations and experiences
Disparities in socioeconomic outcomes and integration patterns Unique
challenges faced by specific national groups

**TODO:** Questions to answer:

1.  Which countries send the most skilled workers, which have the most
    educated people?

2.  Differences in age, gender, and education levels among various
    national groups

3.  Geographic distribution and settlement patterns within the United
    States

4.  Healthcare access and outcomes Housing conditions

5.  Who are the people who choose to stay, and why do they stay?

### Hispanic Migrants in the United States

Table 1 presents sociodemographics of migrants from these countries
living in the U.S.

Things to talk about:

-   Which migrant groups are most educated and likely to acculturate?

    -   most/least likely to have a university degree

    -   most/least likely to have learned English

    -   most/least likely to become naturalized citizens

        -   zoom in on how age at migration impacts these things

-   Compare these groups to native born and migrants from non-hispanic
    countries

-   Which groups are youngest, oldest?

-   which groups are more likely to report being married?

-   which groups are more likely to have migrated at younger ages,
    earlier cohorts?

-   largest/smallest household size?

### Hispanics in their native Countries

Areas to focus on:

-   comparing migrant in US directly to their native country
    counterparts

    -   in the ways we outlined above, except without migration measures
        (obviously)

-   compare men and women to each other

## Discussion {#sec-discussion}

This study will provide a comprehensive sociodemographic comparison of
older adult Hispanic populations both in their countries of origin and
as immigrants in the United States. The analysis so far reveals
significant variations in education levels marital status and migration
patterns across different Hispanic subgroups. These findings have
important implications for understanding the diverse experiences of
Hispanic older adults and for informing policies related to healthy
aging and caregiving. The ongoing analysis (to be reported in the full
paper) is expanding this analysis to further examine patterns by
immigration cohort, also using multivariate regression to better parse
mechanisms underlying the observed differences.

That Mexican migrants have fewer years of formal education is a finding
that other researchers have come across [@hanson_us_2023].

The complexity of migration from Latin America to the United States is
underscored by the region's evolving migration landscape, which has seen
a dramatic increase in intra-regional movement and return migration
since 2010, challenging the traditional narrative of unidirectional
flows to North America and Europe while still maintaining significant
outward migration patterns [@tanco_dramatic_2023]. Additionally, this
paper does not capture return-migrants to Latin America. Lastly, this
research considers migrant populations and host countries pre-pandemic,
which is markedly different than post-pandemic patterns
[@hanson_us_2023].

\begin{landscape} 
\newgeometry{layoutwidth=297mm, layoutheight=210mm, left=20mm, right=20mm, top=20mm, bottom=20mm, footskip=15mm}

% country features table (table 1)

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Latin American Development Indicators$^1$} 
\begin{tabular}{>{\raggedright\arraybackslash}p{5cm}|cccccc}
  \hline
Country & Total$^2$ & Percent of Migrants & GDP Per Capita$^3$ & Life Expectancy at 60$^4$ & Infant Mortality Rate (1950) & Infant Mortality Rate (2019) \\ 
  \hline
Mexico and Carribean Countries &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{Cuba}} & 46,2503 & 11.24 & 9,605 & 21.57 & 87.12 & 4.89 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.8cm}|}{\makebox[3.8cm][r]{Dominican Republic}} & 248,511 & 6.04 & 10,717 & 22.60 & 63.00 & 4.14 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.75cm}|}{\makebox[1.75cm][r]{Mexico}} & 1,809,510 & 43.99 & 13,790 & 22.20 & 96.00 & 10.79 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.5cm}|}{\makebox[2.5cm][r]{Puerto Rico}} & 540,375 & 13.14 & 36,779 & 25.32 & 70.53 & 5.31 \\ 
Central American Countries &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{4.4cm}|}{\makebox[2.5cm][r]{Belize/British Honduras}} & 1,912 & 0.05 & 7,460 & 21.69 & 89.34 & 12.42 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.35cm}|}{\makebox[2.35cm][r]{Costa Rica}} & 20,884 & 0.51 & 16,942 & 24.52 & 80.94 & 7.29 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.45cm}|}{\makebox[2.45cm][r]{El Salvador}} & 198,955 & 4.84 & 5,391 & 22.01 & 78.05 & 14.05 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.4cm}|}{\makebox[2.4cm][r]{Guatemala}} & 99,842 & 2.43 & 5,762 & 20.65 & 107.00 & 18.54 \\
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Honduras}} & 60,125 & 1.46 & 3,231 & 18.13 & 86.00 & 14.66 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Nicaragua}} & 60,186 & 1.46 & 2,612 & 24.50 & 55.14 & 12.59 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.0cm}|}{\makebox[2.0cm][r]{Panama}} & 33,245 & 0.81 & 18,686 & 23.98 & 53.02 & 14.27 \\ 
South Americans &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.25cm}|}{\makebox[2.25cm][r]{Argentina}} & 48,615 & 1.18 & 14,187 & 21.59 & 68.00 & 7.75 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.8cm}|}{\makebox[1.8cm][r]{Bolivia}} & 16,749 & 0.41 & 3,686 & 19.42 & 182.16 & 28.83 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.65cm}|}{\makebox[1.65cm][r]{Brazil}} & 7,814 & 0.19 & 10,294 & 21.32 & 143.77 & 11.81 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.55cm}|}{\makebox[1.55cm][r]{Chile}} & 27,920 & 0.68 & 17,067 & 24.57 & 139.00 & 6.55 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Colombia}} & 194,022 & 4.72 & 6,947 & 22.69 & 97.33 & 9.36 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Ecuador}} & 91,850 & 2.23 & 6,609 & 22.83 & 144.02 & 10.15 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{4.4cm}|}{\makebox[4.4cm][r]{Guyana/British Guiana}} & 2,234 & 0.05 & 20,765 & 18.01 & 82.80 & 11.40 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.51cm}|}{\makebox[1.51cm][r]{Haiti}} & 1,739 & 0.04 & 1,705 & 16.25 & 237.19 & 53.03 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Jamaica}} & 2,627 & 0.06 & 6,839 & 18.66 & 91.87 & 11.56 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Paraguey}} & 3,214 & 0.08 & 6,276 & 21.01 & 75.69 & 9.45 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{Peru}} & 116,599 & 2.83 & 7,906 & 23.37 & 164.76 & 16.01 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{4.0cm}|}{\makebox[4.0cm][r]{Trinidad and Tobago}} & 2,120 & 0.05 & 20,016 & 21.44 & 74.65 & 21.55 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.1cm}|}{\makebox[2.1cm][r]{Uruguey}} & 12,472 & 0.30 & 22,797 & 21.71 & 62.51 & 5.64 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Venezuela}} & 43,299 & 1.05 & 15,943 & 20.67 & 80.00 & 25.54 \\ 
   \hline
\end{tabular}
\begin{tablenotes}
\footnotesize
\item[1] Excludes non-latin American countries  and those with <1500 hispanic immigrants to US.
\item[2] Number of migrants to the US from sending countries was tabulated using the 2016-2020 American Community Survey.
\item[3] GDP data is from 2019; source: .
\item[4] Life expectancy data is from 2019; source: .
\end{tablenotes}
\end{threeparttable}
\end{table}


% table 2

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Sociodemographic Comparison of Hispanics in the U.S. by Birth Country (2016-20 ACS)$^1$} 
\begingroup\small
\begin{tabular}{>{\raggedright\arraybackslash}p{3.2cm}|lcccccc|cccc}
& \multicolumn{7}{c|}{Immigrants} & \multicolumn{4}{c}{Native Born} \\
\cline{2-12}
& \multicolumn{7}{c|}{} & \multicolumn{1}{c}{} & \multicolumn{3}{c}{Non-Hispanic} \\
  \hline
Demographics & Mexico & Puerto Rico$^2$ & Dominican Republic & Cuba & Central America & Latin America$^3$ & Other Countries & Hispanic$^4$ & Black & White & Other \\ 
  \hline
Age &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }}& 0.6 & 0.47 & 0.6 & 0.43 & 0.63 & 0.56 & 0.52 & 0.59 & 0.58 & 0.5 & 0.57 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }}& 0.27 & 0.35 & 0.26 & 0.31 & 0.25 & 0.3 & 0.3 & 0.27 & 0.28 & 0.32 & 0.28 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }}& 0.1 & 0.15 & 0.11 & 0.21 & 0.1 & 0.12 & 0.14 & 0.12 & 0.11 & 0.14 & 0.12 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }}& 0.02 & 0.03 & 0.03 & 0.05 & 0.02 & 0.03 & 0.04 & 0.03 & 0.03 & 0.04 & 0.03 \\ 
  Education Completed &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }}& 0.35 & 0.14 & 0.25 & 0.1 & 0.24 & 0.08 & 0.09 & 0.07 & 0.03 & 0.01 & 0.03 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }}& 0.31 & 0.24 & 0.26 & 0.19 & 0.23 & 0.11 & 0.09 & 0.15 & 0.14 & 0.06 & 0.08 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }}& 0.24 & 0.39 & 0.32 & 0.41 & 0.35 & 0.47 & 0.38 & 0.5 & 0.54 & 0.51 & 0.47 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }}& 0.08 & 0.18 & 0.13 & 0.27 & 0.15 & 0.31 & 0.42 & 0.23 & 0.25 & 0.39 & 0.38 \\ 
  Household &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }}& 3.32 & 2.31 & 2.87 & 2.46 & 3.14 & 2.73 & 2.65 & 2.37 & 2.06 & 1.95 & 2.27 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }}& 0.16 & 0.32 & 0.24 & 0.27 & 0.18 & 0.21 & 0.21 & 0.28 & 0.39 & 0.29 & 0.31 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }}& 0.51 & 0.31 & 0.45 & 0.32 & 0.48 & 0.4 & 0.35 & 0.28 & 0.24 & 0.14 & 0.25 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }}& 0.56 & 0.42 & 0.41 & 0.44 & 0.46 & 0.52 & 0.59 & 0.49 & 0.35 & 0.59 & 0.48 \\ 
  Age Migrated &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.4cm}|}{\makebox[2.4cm][r]{Less than 15 }}& 0.11 & 0.29 & 0.06 & 0.17 & 0.06 & 0.07 & 0.13 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{15 - 23 }}& 0.31 & 0.3 & 0.19 & 0.16 & 0.23 & 0.2 & 0.2 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{24 - 49 }}& 0.45 & 0.25 & 0.52 & 0.42 & 0.56 & 0.51 & 0.47 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.6cm}|}{\makebox[2.6cm][r]{50 and Above }}& 0.13 & 0.16 & 0.23 & 0.25 & 0.15 & 0.22 & 0.2 & - & - & - & - \\ 
  Migration Cohort &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Before 1965 }}& 0.15 & 0.41 & 0.08 & 0.25 & 0.09 & 0.11 & 0.21 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1965 - 1979 }}& 0.45 & 0.28 & 0.33 & 0.35 & 0.37 & 0.34 & 0.31 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1980 - 1999 }}& 0.33 & 0.18 & 0.43 & 0.28 & 0.46 & 0.36 & 0.35 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.1cm}|}{\makebox[2.1cm][r]{After 1999 }}& 0.12 & 0.14 & 0.2 & 0.21 & 0.14 & 0.23 & 0.17 & - & - & - & - \\ 
  Acculturation &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{Citizen }}& 0.54 & - & 0.68 & 0.8 & 0.66 & 0.71 & 0.74 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3cm}|}{\makebox[3cm][r]{English Speakers }}& 0.73 & 0.91 & 0.69 & 0.76 & 0.82 & 0.87 & 0.93 & 0.99 & - & - & - \\ 
  N & 79,658 & 23,021 & 8,980 & 21,242 & 20,064 & 25,003 & 352,960 & 120,724 & 313,063 & 3,165,675 & 94,162 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] See definitions for all categories in the definitions page (x).
\item[2] A Puerto Rican migrant is defined as someone who moves from Puerto Rico to mainland US.
\item[3] The Latin America category excludes our four countries of interest as well as Central America.
\item[4] Anyone not born in Latin America is excluded from the "Hispanic" category.
category.
\end{tablenotes}
\end{threeparttable}
\end{table}

% table 3

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Summary Statistics by Country and Sex For Hispanics in Their Native Countries$^{1,2,3}$} 
\begingroup\small
\begin{tabular}{l|>{\raggedright\arraybackslash}p{3.2cm}|ccccccccc}
  \hline
Gender & Demographics & Mexicans & US Mexican-born & Puerto Ricans & US Puerto-Rican-born & Dominicans & US Dominican-born & Cubans & US Cuban-born \\ 
  \hline
Female & Age &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }} & 0.53 & 0.57 & 0.5 & 0.57 & 0.52 & 0.59 & 0.5 & 0.37 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }} & 0.31 & 0.29 & 0.32 & 0.28 & 0.31 & 0.27 & 0.31 & 0.36 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }} & 0.13 & 0.11 & 0.15 & 0.13 & 0.14 & 0.11 & 0.15 & 0.23 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }} & 0.03 & 0.03 & 0.03 & 0.03 & 0.04 & 0.03 & 0.04 & 0.04 \\ 
   & Education Completed &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.61 & 0.43 & 0.26 & 0.18 & 0.72 & 0.34 & 0.27 & 0.12 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.29 & 0.32 & 0.25 & 0.3 & 0.18 & 0.31 & 0.49 & 0.26 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.07 & 0.23 & 0.36 & 0.44 & 0.07 & 0.3 & 0.17 & 0.47 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.03 & 0.03 & 0.13 & 0.09 & 0.04 & 0.06 & 0.06 & 0.15 \\ 
   & Household &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }} & 3.56 & 3.57 & 2.23 & 2.37 & 3.55 & 3.11 & 3.01 & 2.48 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }} & 0.13 & 0.16 & 0.27 & 0.32 & 0.12 & 0.25 & 0.14 & 0.29 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }} & 0.58 & 0.42 & 0.29 & 0.31 & 0.55 & 0.45 & 0.52 & 0.3 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }} & 0.46 & 0.47 & 0.42 & 0.35 & 0.39 & 0.3 & 0.46 & 0.35 \\ 
   \hline
   & N & 624,788 & 6,055 & 5,267 & 2,148 & 44,053 & 728 & 107,811 & 2,211 \\ 
   \hline
  Male & Age &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }} & 0.54 & 0.63 & 0.54 & 0.59 & 0.54 & 0.6 & 0.52 & 0.43 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }} & 0.31 & 0.27 & 0.32 & 0.3 & 0.3 & 0.3 & 0.32 & 0.35 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }} & 0.12 & 0.09 & 0.13 & 0.09 & 0.12 & 0.09 & 0.13 & 0.2 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }} & 0.03 & 0.02 & 0.02 & 0.02 & 0.03 & 0.01 & 0.03 & 0.02 \\ 
   & Education Completed &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.56 & 0.44 & 0.21 & 0.17 & 0.67 & 0.26 & 0.21 & 0.12 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.29 & 0.3 & 0.27 & 0.29 & 0.21 & 0.3 & 0.48 & 0.24 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.07 & 0.21 & 0.38 & 0.44 & 0.07 & 0.33 & 0.23 & 0.46 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.08 & 0.05 & 0.14 & 0.1 & 0.05 & 0.11 & 0.08 & 0.17 \\ 
   & Household &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }} & 3.7 & 3.68 & 2.4 & 2.55 & 3.56 & 3.5 & 2.95 & 2.53 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }} & 0.11 & 0.13 & 0.18 & 0.25 & 0.16 & 0.16 & 0.17 & 0.22 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }} & 0.56 & 0.34 & 0.24 & 0.25 & 0.5 & 0.39 & 0.43 & 0.2 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }} & 0.74 & 0.75 & 0.67 & 0.61 & 0.68 & 0.67 & 0.67 & 0.66 \\ 
   \hline
   & N & 572,708 & 5,038 & 3,989 & 1,614 & 41,426 & 427 & 96,337 & 1,675 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] US data is from the 2016-2020 American Community Survey.
\item[2] All international Census data is from 2010, except for Cuba which is from 2012.
\item[3] See definitions for all categories in the definitions page (x).
\end{tablenotes}
\end{threeparttable}
\end{table}

\end{landscape}

\newpage

## Appendix {#sec-Appendix}

\newpage

### Tables

\begin{landscape} 
\newgeometry{layoutwidth=297mm, layoutheight=210mm, left=20mm, right=20mm, top=20mm, bottom=20mm, footskip=15mm}

%table 2, females only

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Sociodemographic Comparison of Hispanics in the U.S. by Birth Country (2016-20 ACS)$^1$: Females} 
\begingroup\small
\begin{tabular}{>{\raggedright\arraybackslash}p{3.2cm}|lcccccc|cccc}
  \hline
Demographics & Mexico & Puerto Rico$^2$ & Dominican Republic & Cuba & Central America & Latin America$^3$ & Other Countries & Hispanic$^4$ & Black & White & Other \\ 
  \hline
Age &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }}& 0.57 & 0.45 & 0.58 & 0.4 & 0.63 & 0.56 & 0.52 & 0.59 & 0.55 & 0.48 & 0.56 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }}& 0.28 & 0.35 & 0.27 & 0.31 & 0.25 & 0.3 & 0.3 & 0.27 & 0.28 & 0.31 & 0.27 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }}& 0.12 & 0.16 & 0.12 & 0.23 & 0.1 & 0.12 & 0.14 & 0.12 & 0.13 & 0.15 & 0.13 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }}& 0.03 & 0.04 & 0.03 & 0.06 & 0.02 & 0.03 & 0.04 & 0.03 & 0.04 & 0.05 & 0.04 \\ 
  Education Completed &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }}& 0.36 & 0.14 & 0.26 & 0.1 & 0.24 & 0.08 & 0.09 & 0.07 & 0.02 & 0.01 & 0.03 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }}& 0.31 & 0.24 & 0.27 & 0.19 & 0.23 & 0.11 & 0.09 & 0.15 & 0.14 & 0.06 & 0.09 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }}& 0.24 & 0.39 & 0.31 & 0.42 & 0.35 & 0.47 & 0.38 & 0.5 & 0.54 & 0.54 & 0.48 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }}& 0.07 & 0.19 & 0.12 & 0.26 & 0.15 & 0.31 & 0.42 & 0.23 & 0.26 & 0.36 & 0.37 \\ 
  Household &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }}& 3.29 & 2.25 & 2.78 & 2.44 & 3.14 & 2.73 & 2.65 & 2.37 & 2.05 & 1.89 & 2.26 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }}& 0.17 & 0.35 & 0.26 & 0.3 & 0.18 & 0.21 & 0.21 & 0.28 & 0.41 & 0.35 & 0.33 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }}& 0.51 & 0.33 & 0.46 & 0.35 & 0.48 & 0.4 & 0.35 & 0.28 & 0.27 & 0.15 & 0.27 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }}& 0.47 & 0.32 & 0.29 & 0.33 & 0.46 & 0.52 & 0.59 & 0.49 & 0.27 & 0.51 & 0.41 \\ 
  Age Migrated &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.4cm}|}{\makebox[2.4cm][r]{Less than 15 }}& 0.11 & 0.28 & 0.06 & 0.15 & 0.06 & 0.07 & 0.13 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{15 - 23 }}& 0.28 & 0.29 & 0.19 & 0.16 & 0.23 & 0.2 & 0.2 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{24 - 49 }}& 0.45 & 0.26 & 0.51 & 0.41 & 0.56 & 0.51 & 0.47 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.6cm}|}{\makebox[2.6cm][r]{50 and Above }}& 0.16 & 0.17 & 0.25 & 0.28 & 0.15 & 0.22 & 0.2 & - & - & - & - \\ 
  Migration Cohort &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Before 1965 }}& 0.16 & 0.41 & 0.09 & 0.24 & 0.09 & 0.11 & 0.21 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1965 - 1979 }}& 0.42 & 0.27 & 0.31 & 0.36 & 0.37 & 0.34 & 0.31 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1980 - 1999 }}& 0.33 & 0.19 & 0.43 & 0.23 & 0.46 & 0.36 & 0.35 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.1cm}|}{\makebox[2.1cm][r]{After 1999 }}& 0.14 & 0.15 & 0.21 & 0.23 & 0.14 & 0.23 & 0.17 & - & - & - & - \\ 
  Acculturation &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{Citizen }}& 0.55 & - & 0.7 & 0.82 & 0.66 & 0.71 & 0.74 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3cm}|}{\makebox[3cm][r]{English Speakers }}& 0.68 & 0.9 & 0.65 & 0.72 & 0.82 & 0.87 & 0.93 & 0.99 & - & - & - \\ 
  N & 42,189 & 13,298 & 5,390 & 11,852 & 20,064 & 25,003 & 352,960 & 120,724 & 182,312 & 1,695,106 & 51,222 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] See definitions for all categories in the definitions page (x).
\item[2] A Puerto Rican migrant is defined as someone who moves from Puerto Rico to mainland US.
\item[3] The Latin America category excludes our four countries of interest as well as Central America.
\item[4] Anyone not born in Latin America is excluded from the "Hispanic" category.
\end{tablenotes}
\end{threeparttable}
\end{table}


% table 1, males only

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Sociodemographic Comparison of Hispanics in the U.S. by Birth Country (2016-20 ACS)$^1$: Males} 
\begingroup\small
\begin{tabular}{>{\raggedright\arraybackslash}p{3.2cm}|lcccccc|cccc}
  \hline
Demographics & Mexico & Puerto Rico$^2$ & Dominican Republic & Cuba & Central America & Latin America$^3$ & Other Countries & Hispanic$^4$ & Black & White & Other \\ 
  \hline
Age &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }}& 0.63 & 0.5 & 0.63 & 0.47 & 0.63 & 0.56 & 0.52 & 0.59 & 0.61 & 0.53 & 0.59 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }}& 0.26 & 0.35 & 0.26 & 0.31 & 0.25 & 0.3 & 0.3 & 0.27 & 0.28 & 0.32 & 0.28 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }}& 0.09 & 0.13 & 0.1 & 0.18 & 0.1 & 0.12 & 0.14 & 0.12 & 0.1 & 0.13 & 0.11 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }}& 0.02 & 0.02 & 0.02 & 0.04 & 0.02 & 0.03 & 0.04 & 0.03 & 0.02 & 0.03 & 0.02 \\ 
  Education Completed &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }}& 0.35 & 0.14 & 0.23 & 0.09 & 0.24 & 0.08 & 0.09 & 0.07 & 0.03 & 0.01 & 0.03 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }}& 0.3 & 0.25 & 0.25 & 0.18 & 0.23 & 0.11 & 0.09 & 0.15 & 0.15 & 0.06 & 0.08 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }}& 0.24 & 0.4 & 0.34 & 0.4 & 0.35 & 0.47 & 0.38 & 0.5 & 0.55 & 0.47 & 0.45 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }}& 0.09 & 0.17 & 0.14 & 0.29 & 0.15 & 0.31 & 0.42 & 0.23 & 0.23 & 0.42 & 0.4 \\ 
  Household &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }}& 3.35 & 2.4 & 3.01 & 2.49 & 3.14 & 2.73 & 2.65 & 2.37 & 2.07 & 2.02 & 2.28 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }}& 0.15 & 0.26 & 0.2 & 0.23 & 0.18 & 0.21 & 0.21 & 0.28 & 0.36 & 0.23 & 0.28 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }}& 0.5 & 0.28 & 0.44 & 0.28 & 0.48 & 0.4 & 0.35 & 0.28 & 0.19 & 0.14 & 0.22 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }}& 0.67 & 0.56 & 0.59 & 0.59 & 0.46 & 0.52 & 0.59 & 0.49 & 0.47 & 0.68 & 0.58 \\ 
  Age Migrated &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.4cm}|}{\makebox[2.4cm][r]{Less than 15 }}& 0.12 & 0.3 & 0.07 & 0.19 & 0.06 & 0.07 & 0.13 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{15 - 23 }}& 0.34 & 0.31 & 0.19 & 0.15 & 0.23 & 0.2 & 0.2 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{24 - 49 }}& 0.44 & 0.24 & 0.52 & 0.44 & 0.56 & 0.51 & 0.47 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.6cm}|}{\makebox[2.6cm][r]{50 and Above }}& 0.1 & 0.15 & 0.21 & 0.22 & 0.15 & 0.22 & 0.2 & - & - & - & - \\ 
  Migration Cohort &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Before 1965 }}& 0.15 & 0.42 & 0.07 & 0.26 & 0.09 & 0.11 & 0.21 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1965 - 1979 }}& 0.48 & 0.3 & 0.34 & 0.35 & 0.37 & 0.34 & 0.31 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1980 - 1999 }}& 0.32 & 0.18 & 0.44 & 0.33 & 0.46 & 0.36 & 0.35 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.1cm}|}{\makebox[2.1cm][r]{After 1999 }}& 0.1 & 0.13 & 0.19 & 0.19 & 0.14 & 0.23 & 0.17 & - & - & - & - \\ 
  Acculturation &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{Citizen }}& 0.53 & - & 0.66 & 0.77 & 0.66 & 0.71 & 0.74 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3cm}|}{\makebox[3cm][r]{English Speakers }}& 0.78 & 0.94 & 0.74 & 0.8 & 0.82 & 0.87 & 0.93 & 0.99 & - & - & - \\ 
  N & 37,469 & 9,723 & 3,590 & 9,390 & 20,064 & 25,003 & 352,960 & 120,724 & 130,751 & 1,470,569 & 42,940 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] See definitions for all categories in the definitions page (x).
\item[2] A Puerto Rican migrant is defined as someone who moves from Puerto Rico to mainland US.
\item[3] The Latin America category excludes our four countries of interest as well as Central America.
\item[4] Anyone not born in Latin America is excluded from the "Hispanic" category.
\end{tablenotes}
\end{threeparttable}
\end{table}

% table 2, using 2010 data

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Sociodemographic Comparison of Hispanics in the U.S. by Birth Country (2006-10 ACS)$^1$} 
\begingroup\small
\begin{tabular}{>{\raggedright\arraybackslash}p{3.2cm}|lcccccc|cccc}
  \hline
Demographics & Mexico & Puerto Rico$^2$ & Dominican Republic & Cuba & Central America & Latin America$^3$ & Other Countries & Hispanic$^4$ & Black & White & Other \\ 
  \hline
Age &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }}& 0.6 & 0.58 & 0.59 & 0.4 & 0.63 & 0.57 & 0.51 & 0.55 & 0.55 & 0.5 & 0.55 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }}& 0.28 & 0.29 & 0.28 & 0.35 & 0.24 & 0.29 & 0.3 & 0.28 & 0.29 & 0.29 & 0.27 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }}& 0.1 & 0.11 & 0.1 & 0.22 & 0.1 & 0.12 & 0.16 & 0.15 & 0.13 & 0.17 & 0.15 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }}& 0.02 & 0.03 & 0.02 & 0.03 & 0.03 & 0.02 & 0.03 & 0.02 & 0.03 & 0.04 & 0.03 \\ 
  Education Completed &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }}& 0.43 & 0.18 & 0.31 & 0.12 & 0.3 & 0.11 & 0.11 & 0.11 & 0.05 & 0.01 & 0.04 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }}& 0.31 & 0.29 & 0.31 & 0.25 & 0.27 & 0.17 & 0.13 & 0.22 & 0.24 & 0.11 & 0.14 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }}& 0.22 & 0.44 & 0.31 & 0.47 & 0.35 & 0.53 & 0.47 & 0.55 & 0.58 & 0.62 & 0.59 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }}& 0.04 & 0.09 & 0.08 & 0.16 & 0.08 & 0.2 & 0.3 & 0.12 & 0.14 & 0.26 & 0.24 \\ 
  Household &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }}& 3.62 & 2.45 & 3.26 & 2.5 & 3.4 & 2.84 & 2.63 & 2.41 & 2.14 & 1.92 & 2.23 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }}& 0.14 & 0.29 & 0.22 & 0.26 & 0.2 & 0.2 & 0.23 & 0.25 & 0.37 & 0.3 & 0.31 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }}& 0.38 & 0.28 & 0.43 & 0.25 & 0.38 & 0.34 & 0.26 & 0.23 & 0.22 & 0.12 & 0.2 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }}& 0.6 & 0.46 & 0.44 & 0.49 & 0.47 & 0.54 & 0.61 & 0.55 & 0.37 & 0.6 & 0.52 \\ 
  Age Migrated &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.4cm}|}{\makebox[2.4cm][r]{Less than 15 }}& 0.09 & 0.27 & 0.03 & 0.06 & 0.03 & 0.04 & 0.11 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{15 - 23 }}& 0.23 & 0.34 & 0.15 & 0.15 & 0.15 & 0.19 & 0.2 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{24 - 49 }}& 0.47 & 0.24 & 0.53 & 0.54 & 0.57 & 0.52 & 0.46 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.6cm}|}{\makebox[2.6cm][r]{50 and Above }}& 0.21 & 0.15 & 0.28 & 0.25 & 0.25 & 0.25 & 0.24 & - & - & - & - \\ 
  Migration Cohort &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Before 1965 }}& 0.26 & 0.57 & 0.14 & 0.29 & 0.12 & 0.19 & 0.31 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1965 - 1979 }}& 0.41 & 0.22 & 0.37 & 0.41 & 0.4 & 0.39 & 0.32 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1980 - 1999 }}& 0.26 & 0.13 & 0.37 & 0.27 & 0.43 & 0.31 & 0.3 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.1cm}|}{\makebox[2.1cm][r]{After 1999 }}& 0.11 & 0.1 & 0.15 & 0.13 & 0.12 & 0.14 & 0.11 & - & - & - & - \\ 
  Acculturation &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{Citizen }}& 0.5 & - & 0.58 & 0.76 & 0.56 & 0.66 & 0.73 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3cm}|}{\makebox[3cm][r]{English Speakers }}& 0.64 & 0.9 & 0.63 & 0.71 & 0.72 & 0.85 & 0.91 & 0.98 & - & - & 0.99 \\ 
  N & 11,093 & 3,762 & 1,155 & 3,886 & 1,753 & 4,535 & 54,051 & 16,527 & 49,156 & 528,779 & 11,860 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] See definitions for all categories in the definitions page (x).
\item[2] A Puerto Rican migrant is defined as someone who moves from Puerto Rico to mainland US.
\item[3] The Latin America category excludes our four countries of interest as well as Central America.
\item[4] Anyone not born in Latin America is excluded from the "Hispanic" category.
\end{tablenotes}
\end{threeparttable}
\end{table}

% table 2, focusing purely on those 25 and above

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Sociodemographic Comparison of Hispanics in the U.S. by Birth Country (2016-20 ACS)$^1$: Migrated After Age 24} 
\begingroup\small
\begin{tabular}{>{\raggedright\arraybackslash}p{3.2cm}|lcccccc|cccc}
  \hline
Demographics & Mexico & Puerto Rico$^2$ & Dominican Republic & Cuba & Central America & Latin America$^3$ & Other Countries & Hispanic$^4$ & Black & White & Other \\ 
  \hline
Age &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }}& 0.52 & 0.46 & 0.56 & 0.34 & 0.59 & 0.53 & 0.49 & 0.59 & 0.58 & 0.5 & 0.57 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }}& 0.31 & 0.31 & 0.27 & 0.32 & 0.27 & 0.29 & 0.31 & 0.27 & 0.28 & 0.32 & 0.28 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }}& 0.14 & 0.17 & 0.13 & 0.27 & 0.12 & 0.15 & 0.16 & 0.12 & 0.11 & 0.14 & 0.12 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }}& 0.03 & 0.05 & 0.03 & 0.07 & 0.03 & 0.03 & 0.04 & 0.03 & 0.03 & 0.04 & 0.03 \\ 
  Education Completed &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }}& 0.4 & 0.17 & 0.28 & 0.12 & 0.29 & 0.1 & 0.11 & 0.07 & 0.03 & 0.01 & 0.03 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }}& 0.3 & 0.22 & 0.28 & 0.23 & 0.24 & 0.12 & 0.1 & 0.15 & 0.14 & 0.06 & 0.08 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }}& 0.2 & 0.37 & 0.3 & 0.4 & 0.31 & 0.45 & 0.36 & 0.5 & 0.54 & 0.51 & 0.47 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }}& 0.07 & 0.21 & 0.12 & 0.23 & 0.14 & 0.3 & 0.41 & 0.23 & 0.25 & 0.39 & 0.38 \\ 
  Household &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }}& 3.45 & 2.44 & 2.93 & 2.57 & 3.24 & 2.82 & 2.86 & 2.37 & 2.06 & 1.95 & 2.27 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }}& 0.15 & 0.3 & 0.23 & 0.27 & 0.18 & 0.2 & 0.19 & 0.28 & 0.39 & 0.29 & 0.31 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }}& 0.53 & 0.35 & 0.47 & 0.35 & 0.5 & 0.43 & 0.4 & 0.28 & 0.24 & 0.14 & 0.25 \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }}& 0.53 & 0.4 & 0.4 & 0.41 & 0.44 & 0.51 & 0.58 & 0.49 & 0.35 & 0.59 & 0.48 \\ 
  Age Migrated &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{24 - 49 }}& 0.77 & 0.61 & 0.69 & 0.63 & 0.79 & 0.7 & 0.7 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.6cm}|}{\makebox[2.6cm][r]{50 and Above }}& 0.23 & 0.39 & 0.31 & 0.37 & 0.21 & 0.3 & 0.3 & - & - & - & - \\ 
  Migration Cohort &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.3cm}|}{\makebox[2.3cm][r]{Before 1965 }}& 0.03 & 0.05 & 0.03 & 0.08 & 0.02 & 0.03 & 0.04 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1965 - 1979 }}& 0.29 & 0.22 & 0.2 & 0.34 & 0.24 & 0.23 & 0.25 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{1980 - 1999 }}& 0.52 & 0.43 & 0.55 & 0.38 & 0.61 & 0.47 & 0.5 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.1cm}|}{\makebox[2.1cm][r]{After 1999 }}& 0.2 & 0.35 & 0.27 & 0.32 & 0.19 & 0.31 & 0.25 & - & - & - & - \\ 
  Acculturation &  &  &  &  &  &  &  &  &  &  &  \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.6cm}|}{\makebox[1.6cm][r]{Citizen }}& 0.45 & - & 0.64 & 0.75 & 0.61 & 0.67 & 0.73 & - & - & - & - \\ 
  \multicolumn{1}{>{\raggedleft\arraybackslash}p{3cm}|}{\makebox[3cm][r]{English Speakers }}& 0.64 & 0.84 & 0.62 & 0.66 & 0.77 & 0.84 & 0.9 & 0.99 & - & - & - \\ 
  N & 44,152 & 9,159 & 6,541 & 13,647 & 13,655 & 17,935 & 227,703 & 120,724 & 313,063 & 3,165,675 & 94,162 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] See definitions for all categories in the definitions page (x).
\item[2] A Puerto Rican migrant is defined as someone who moves from Puerto Rico to mainland US.
\item[3] The Latin America category excludes our four countries of interest as well as Central America.
\item[4] Anyone not born in Latin America is excluded from the "Hispanic" category.
\end{tablenotes}
\end{threeparttable}
\end{table}


% table 3 age-standardized

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Summary Statistics by Country and Sex For Hispanics in Their Native Countries (Age Standardized)$^{1,2,3}$} 
\begingroup\small
\begin{tabular}{l>{\raggedright\arraybackslash}p{3.2cm}|cccccccc}
  \hline
Gender & Demographics & Mexicans & US Mexican-born & Puerto Ricans & US Puerto-Rican-born & Dominicans & US Dominican-born & Cubans & US Cuban-born \\ 
  \hline
Female & Age &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }} & 0.54 & 0.57 & 0.47 & 0.57 & 0.52 & 0.59 & 0.5 & 0.37 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }} & 0.3 & 0.29 & 0.33 & 0.28 & 0.31 & 0.27 & 0.31 & 0.36 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }} & 0.13 & 0.11 & 0.16 & 0.13 & 0.14 & 0.11 & 0.15 & 0.23 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }} & 0.03 & 0.03 & 0.04 & 0.03 & 0.04 & 0.03 & 0.04 & 0.04 \\ 
   & Education Completed &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.53 & 0.43 & 0.21 & 0.18 & 0.72 & 0.34 & 0.28 & 0.12 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.33 & 0.32 & 0.23 & 0.3 & 0.17 & 0.31 & 0.49 & 0.26 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.09 & 0.23 & 0.4 & 0.44 & 0.07 & 0.3 & 0.17 & 0.47 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.05 & 0.03 & 0.17 & 0.09 & 0.03 & 0.06 & 0.06 & 0.15 \\ 
   & Household &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }} & 3.47 & 3.57 & 2.19 & 2.37 & 3.54 & 3.11 & 3.02 & 2.48 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }} & 0.14 & 0.16 & 0.29 & 0.32 & 0.13 & 0.25 & 0.14 & 0.29 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }} & 0.58 & 0.42 & 0.28 & 0.31 & 0.55 & 0.45 & 0.52 & 0.3 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }} & 0.44 & 0.47 & 0.4 & 0.35 & 0.38 & 0.3 & 0.45 & 0.35 \\ 
   & N & 1,596,847 & 6,055 & 30,154 & 2,148 & 44,053 & 728 & 107,811 & 2,211 \\ 
  Male & Age &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }} & 0.56 & 0.63 & 0.51 & 0.59 & 0.54 & 0.6 & 0.52 & 0.43 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }} & 0.3 & 0.27 & 0.33 & 0.3 & 0.3 & 0.3 & 0.32 & 0.35 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }} & 0.12 & 0.09 & 0.14 & 0.09 & 0.12 & 0.09 & 0.13 & 0.2 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }} & 0.02 & 0.02 & 0.02 & 0.02 & 0.03 & 0.01 & 0.03 & 0.02 \\ 
   & Education Completed &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.47 & 0.44 & 0.17 & 0.17 & 0.67 & 0.26 & 0.2 & 0.12 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.33 & 0.3 & 0.25 & 0.29 & 0.21 & 0.3 & 0.48 & 0.24 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.09 & 0.21 & 0.41 & 0.44 & 0.07 & 0.33 & 0.24 & 0.46 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.11 & 0.05 & 0.17 & 0.1 & 0.05 & 0.11 & 0.09 & 0.17 \\ 
   & Household &  &  &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }} & 3.6 & 3.68 & 2.34 & 2.55 & 3.56 & 3.5 & 2.95 & 2.53 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }} & 0.11 & 0.13 & 0.2 & 0.25 & 0.16 & 0.16 & 0.17 & 0.22 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }} & 0.54 & 0.34 & 0.22 & 0.25 & 0.5 & 0.39 & 0.43 & 0.2 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }} & 0.74 & 0.75 & 0.63 & 0.61 & 0.68 & 0.67 & 0.67 & 0.66 \\ 
   & N & 1,456,521 & 5,038 & 22,856 & 1,614 & 41,426 & 427 & 96,337 & 1,675 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] US data is from the 2016-2020 American Community Survey.
\item[2] All international Census data is from 2010, except for Cuba which is from 2012.
\item[3] See definitions for all categories in the definitions page (x).
\end{tablenotes}
\end{threeparttable}
\end{table}

% 2010 and 2020 mexico, pr, us

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Summary Statistics by Country and Sex For Hispanics in Their Native Countries$^{1,2}$ (2010 and 2020)} 
\begingroup\small
\begin{tabular}{l>{\raggedright\arraybackslash}p{3.2cm}|cccccc}
  \hline
Gender & Demographics & Mexico 2010 & Mexico 2020 & Puerto Rico 2010 & Puerto Rico 2020 & United States 2010 & United States 2020 \\ 
  \hline
Female & Age &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }} & 0.53 & 0.55 & 0.5 & 0.45 & 0.49 & 0.5 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }} & 0.31 & 0.29 & 0.32 & 0.34 & 0.29 & 0.31 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }} & 0.13 & 0.13 & 0.15 & 0.17 & 0.18 & 0.15 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }} & 0.03 & 0.03 & 0.03 & 0.04 & 0.05 & 0.05 \\ 
   & Education Completed &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.61 & 0.45 & 0.26 & 0.15 & 0.04 & 0.03 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.29 & 0.38 & 0.25 & 0.21 & 0.14 & 0.09 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.07 & 0.11 & 0.36 & 0.44 & 0.63 & 0.62 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.03 & 0.07 & 0.13 & 0.2 & 0.2 & 0.26 \\ 
   & Household &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }} & 3.56 & 3.42 & 2.23 & 2.15 & 2.01 & 2.06 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }} & 0.13 & 0.14 & 0.27 & 0.3 & 0.36 & 0.33 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }} & 0.58 & 0.57 & 0.29 & 0.26 & 0.17 & 0.17 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }} & 0.46 & 0.47 & 0.42 & 0.4 & 0.47 & 0.49 \\ 
   & N & 624,788 & 975,534 & 5,267 & 24,887 & 380,399 & 2,292,118 \\ 
  Male & Age &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{60 - 69 }} & 0.54 & 0.56 & 0.54 & 0.48 & 0.55 & 0.54 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{70 - 79 }} & 0.31 & 0.3 & 0.32 & 0.35 & 0.29 & 0.31 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{80 - 89 }} & 0.12 & 0.12 & 0.13 & 0.15 & 0.14 & 0.12 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.5cm}|}{\makebox[1.5cm][r]{90 plus }} & 0.03 & 0.02 & 0.02 & 0.02 & 0.02 & 0.02 \\ 
   & Education Completed &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.56 & 0.4 & 0.21 & 0.15 & 0.04 & 0.03 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.29 & 0.37 & 0.27 & 0.24 & 0.12 & 0.08 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.07 & 0.1 & 0.38 & 0.43 & 0.54 & 0.56 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.08 & 0.13 & 0.14 & 0.18 & 0.29 & 0.32 \\ 
   & Household &  &  &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.7cm}|}{\makebox[2.7cm][r]{Household Size }} & 3.7 & 3.52 & 2.4 & 2.28 & 2.16 & 2.16 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.2cm}|}{\makebox[2.2cm][r]{Lives Alone }} & 0.11 & 0.11 & 0.18 & 0.22 & 0.22 & 0.23 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2.9cm}|}{\makebox[2.9cm][r]{Lives with Child }} & 0.56 & 0.53 & 0.24 & 0.2 & 0.14 & 0.15 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.4cm}|}{\makebox[3.4cm][r]{Married/Cohabiting }} & 0.74 & 0.74 & 0.67 & 0.61 & 0.71 & 0.69 \\ 
   & N & 572,708 & 887,846 & 3,989 & 18,867 & 306,158 & 1,932,434 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] 2010 US data is from the decennial census. 2020 US data is from the 2016-20 American Community Survey. 
\item[2] See definitions for all categories in the definitions page (x).
\end{tablenotes}
\end{threeparttable}
\end{table}

% proportion educated by birth cohort

\begin{table}[ht]
\centering
\begin{threeparttable}
\caption{Educational Attainment of Mexican-Born Individuals by Gender and Location (2010-2020)$^{1,2}$} 
\begingroup\small
\begin{tabular}{l>{\raggedright\arraybackslash}p{3.2cm}|cccc}
  \hline
Gender & Demographics & Mexico 2010 & Mexico 2020 & Mexico-Born US 2010 & Mexico-Born US 2020$^3$ \\ 
  \hline
Female & Education Completed &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.59 & 0.56 & 0.42 & 0.43 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.30 & 0.32 & 0.32 & 0.29 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.07 & 0.08 & 0.23 & 0.20 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.03 & 0.04 & 0.03 & 0.05 \\ 
   & N & 535,289 & 440,990 & 5,314 & 16,897 \\ 
  Male & Education Completed &  &  &  &  \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{3.2cm}|}{\makebox[3.2cm][r]{Less than Primary }} & 0.54 & 0.52 & 0.41 & 0.44 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{1.7cm}|}{\makebox[1.7cm][r]{Primary }} & 0.30 & 0.31 & 0.31 & 0.27 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{Secondary }} & 0.07 & 0.07 & 0.22 & 0.20 \\ 
   & \multicolumn{1}{>{\raggedleft\arraybackslash}p{2cm}|}{\makebox[2cm][r]{University }} & 0.08 & 0.10 & 0.05 & 0.07 \\ 
   & N & 494,127 & 404,169 & 4,569 & 13,531 \\ 
   \hline
\end{tabular}
\endgroup
\begin{tablenotes}
\footnotesize
\item[1] 2010 US data is from the decennial census. 2020 US data is from the 2016-20 American Community Survey.
\item[2] See definitions for all categories in the definitions page (x).
\item[3] The 2020 sample of Mexican-born living in the US excludes people who migrated to the US after 2010.
\end{tablenotes}
\end{threeparttable}
\end{table}

\end{landscape}

\newpage

### Definitions {#sec-definitions}

**English Speaker:** We define an "English speaker" as anyone who says
they speak English, including those who say "yes, but not well."

**Education Levels:** In order to make education categories comparable
to the US. We exclude those who received a GED from these categories.

-   "**Less Than Primary**" includes individuals with education levels
    such as "grade 1" through "grade 5," "kindergarten," "no schooling
    completed," or "nursery school, preschool."

-   "**Primary Completed**" includes those who completed grades 6
    through 11, representing completion of primary education but not
    secondary school.

-   "**Secondary Completed**" includes individuals with a "regular high
    school diploma," partial college experience (e.g., "1 or more years
    of college credit, no degree" or "some college, but less than 1
    year"), or those who attended up to the 12th grade without
    graduating, indicating completion of secondary education or partial
    college.

-   "**University Completed**" includes individuals with higher
    education qualifications such as an associate's degree, bachelor's
    degree, master's degree, doctoral degree, or professional degree
    beyond a bachelor's, representing university-level education or
    higher. Each individual is assigned to one of these categories based
    on their reported education level.

**Household Size:** The household size is a measure of the respondent's
"own family" living in the household, including themselves.

-   "Lives Alone" is defined as a household size of 1.

-   "Lives with Child" refers to respondents who report one of their
    household members as one of their children.

**Married:** The US Census status classification identifies four major
categories: never married, married, widowed, and divorced. These terms
refer to the marital status at the time of the enumeration. The
"married" category is defined as those who responded "married, spouse
present," implying that the spouse lives in the household.

In the International samples, we include those who responded in the
following ways as "married."

-   "married, formally"

-   "married, civil"

-   "married or consensual union

-   "married, religious"

-   "married, civil and religious"

-   "consensual union"

**Citizen:** U.S. citizen by naturalization.

**Hispanic:** People of Hispanic origin, according to the ACS, were
those who indicated that their origin was Mexican, Puerto Rican, Cuban,
Central or South American, or some other Hispanic origin. For this
paper, we excluded anyone not born in Latin America from the "Hispanic"
category.

**Latin America and Caribbean Countries:** Any country in Latin
American, including north, central, and south america, as well as
countries in the Caribbean that speak primarily Spanish.

\newpage
\section*{Acknowledgments}
\addcontentsline{toc}{section}{Acknowledgments}

The authors wish to acknowledge the statistical offices that provided
the underlying data making this research possible: National
Administrative Department of Statistics, Colombia; Office of National
Statistics, Cuba; National Statistics Office, Dominican Republic;
Department of Statistics and Censuses, El Salvador; National Institute
of Statistics, Guatemala; National Institute of Statistics, Honduras;
National Institute of Statistics, Geography, and Informatics, Mexico;
U.S. Bureau of the Census, Puerto Rico; and Bureau of the Census, United
States.

\newpage

\newpage

\% quarto render
"/Users/chrissoria/Documents/Research/us_international_ses/paper/carib_hisp_immigrant_comp.qmd"
--to docx

# References
